#! /bin/sh
#---------------------------------------------------------------------
#
#	File: 	CopyToEffects
#
#	Contains: 	
#
#
#	Written By: 	Elias Keshishoglou on Fri Feb 27 22:13:12 PST 2015
#
#	Copyright ©: 	2015 Elias Keshishoglou all rights reserved.
#
#
#---------------------------------------------------------------------#
# DestDir="/home/GDriveKesh/Music/LiveEffects/"
DestDir="/home/Dropbox/LiveEffects/"

cp LiveMusicApp  ${DestDir}
cp ./KeepLiveMusicRunning.sh  ${DestDir}
rsync -avrx ./LiveMusicRes/ ${DestDir}LiveMusicRes/
cp /home/elias/workspace/MusicFiles/GuitarEffects ${DestDir}
cp /home/elias/workspace/MusicFiles/CreateChartIndex ${DestDir}
cp /home/elias/workspace/MusicFiles/RegenerateCharts ${DestDir}
cp /home/elias/workspace/MusicFiles/ExtractHTML ${DestDir}
cp /home/elias/workspace/MusicFiles/CreateChartFile ${DestDir}
cp /home/elias/workspace/MusicFiles/MyTuxGuitar ${DestDir}
cp /home/elias/workspace/MusicFiles/jack-plumbing ${DestDir}"/Prefs/"



# ~/.hydrogen/hydrogen.conf
# ~/.sooperlooper
# ~/.config/guitarix