GTKMidiInfo GlobalInfo = {
 	{
/*   0 */ {"Chorus", 0xff,   0, GuitarixPort,   1, NoCustom, "None" },
/*   1 */ {"SatrianiComp", 0xff,   1, GuitarixPort,   1, NoCustom, "None" },
/*   2 */ {"CleanBass", 0xff,   2, GuitarixPort,   1, NoCustom, "None" },
/*   3 */ {"FunkyGuitar", 0xff,   3, GuitarixPort,   1, NoCustom, "None" },
/*   4 */ {"MedDist", 0xff,   4, GuitarixPort,   1, NoCustom, "None" },
/*   5 */ {"OctBass", 0xff,   5, GuitarixPort,   1, NoCustom, "None" },
/*   6 */ {"FunkBass", 0xff,   6, GuitarixPort,   1, NoCustom, "None" },
/*   7 */ {"EBell", 0xff,   7, GuitarixPort,   1, NoCustom, "None" },
/*   8 */ {"WahToggle", 0xff,  14, GuitarixPort,   1, cmdSendCC, "None" },
/*   9 */ {"LayoutSwitch", 0xff,   0, FluidPort,   1, cmdBankSelect, "None" },
/*  10 */ {"Piano", SFDSF,  63, FluidPort,   1, NoCustom, "None" },
/*  11 */ {"Honky", SFFluidGM,   3, FluidPort,   1, NoCustom, "None" },
/*  12 */ {"Breath", SFFluidGM,  53, FluidPort,   1, NoCustom, "None" },
/*  13 */ {"Organ", SFFluidGM,  16, FluidPort,   1, NoCustom, "None" },
/*  14 */ {"Flute", SFFlute,  73, FluidPort,   1, NoCustom, "None" },
/*  15 */ {"SynthLead", SFDSF,  43, FluidPort,   1, NoCustom, "None" },
/*  16 */ {"Strings", SFDSF,  85, FluidPort,   1, NoCustom, "None" },
/*  17 */ {"Trumpet", SFDSF,  66, FluidPort,   1, NoCustom, "None" },
/*  18 */ {"Steel Drums", SFFluidGM, 114, FluidPort,   1, NoCustom, "None" },
/*  19 */ {"Walky", SFDSF,   3, FluidPort,   1, NoCustom, "None" },
/*  20 */ {"Drums", 0xff,   1, FluidPort,   1, NoCustom, "None" },
/*  21 */ {"Slap Bass", SFDSF,  24, FluidPort,   1, NoCustom, "None" },
/*  22 */ {"Synth Hard", SFDSF,  60, FluidPort,   1, NoCustom, "None" },
/*  23 */ {"Marimba", SFDSF,  12, FluidPort,   1, NoCustom, "None" },
/*  24 */ {"Breath1", SFDSF,  48, FluidPort,   1, NoCustom, "None" },
/*  25 */ {"Steel DrumsDUP", SFDSF, 114, FluidPort,   1, NoCustom, "None" },
/*  26 */ {"Low Synth", SFDSF,  45, FluidPort,   1, NoCustom, "None" },
/*  27 */ {"Mid0", 0xff,   0, FluidPort,   1, NoCustom, "None" },
/*  28 */ {"Mid-24", 0xff,   2, FluidPort,   1, NoCustom, "None" },
/*  29 */ {"Mid Screen", SFDSF,   0, FluidPort,   1, NoCustom, "None" },
/*  30 */ {"Rak Eff6", 0xff,  11, GuitarixPort,   1, Controller, "None" },
/*  31 */ {"Rak Eff7", 0xff,  13, GuitarixPort,   1, Controller, "None" },
/*  32 */ {"Rak Eff8", 0xff,  15, GuitarixPort,   1, Controller, "None" },
/*  33 */ {"Rak Eff9", 0xff,  17, GuitarixPort,   1, Controller, "None" },
/*  34 */ {"Rak Eff10", 0xff,  18, GuitarixPort,   1, Controller, "None" },
/*  35 */ {"Rak Eff1", 0xff,   0, GuitarixPort,   1, Controller, "None" },
/*  36 */ {"Rak Eff2", 0xff,   2, GuitarixPort,   1, Controller, "None" },
/*  37 */ {"Rak Eff3", 0xff,   4, GuitarixPort,   1, Controller, "None" },
/*  38 */ {"Rak Eff4", 0xff,   6, GuitarixPort,   1, Controller, "None" },
/*  39 */ {"Rak Eff5", 0xff,   8, GuitarixPort,   1, Controller, "None" },
/*  40 */ {"TransStart", 0xff,   0, TransportPort,   1, TransStart, "None" },
/*  41 */ {"TransCont", 0xff,   0, TransportPort,   1, TransCont, "None" },
/*  42 */ {"TransStop", 0xff,   0, TransportPort,   1, TransStop, "None" },
/*  43 */ {"TransBack", 0xff,   0, TransportPort,   1, TransStart, "None" },
/*  44 */ {"TransPos", 0xff,   0, TransportPort,   1, TransStart, "None" },
/*  45 */ {"Tap", 0xff, 121, FluidPort,   1, Controller, "None" },
/*  46 */ {"Midi Tog", 0xff, 122, FluidPort,   1, Controller, "None" },
/*  47 */ {"Tuner", 0xff, 123, FluidPort,   1, Controller, "None" },
/*  48 */ {"AnaOnOff", 0xff, 124, FluidPort,   1, Controller, "None" },
/*  49 */ {"AnaOnOff", 0xff, 124, FluidPort,   1, Controller, "None" },
/*  50 */ {"LP Undo", 0xff,   5, FluidPort,   1, cmdOSC, "None" },
/*  51 */ {"LP 1", SFElias,   1, FluidPort,   1, cmdOSC, "None" },
/*  52 */ {"LP 2", SFSonidoGM,   1, FluidPort,   1, cmdOSC, "None" },
/*  53 */ {"LP 3", SFSynthGM,   1, FluidPort,   1, cmdOSC, "None" },
/*  54 */ {"LP 4", SFVintage,   1, FluidPort,   1, cmdOSC, "None" },
/*  55 */ {"LP Rec", 0xff,   2, FluidPort,   1, cmdOSC, "None" },
/*  56 */ {"LP Pause", 0xff,   3, FluidPort,   1, cmdOSC, "None" },
/*  57 */ {"LP Trig", 0xff,   4, FluidPort,   1, cmdOSC, "None" },
/*  58 */ {"LP Tap", 0xff,  77, FluidPort,   1, cmdOSC, "None" },
/*  59 */ {"LP Add", 0xff,   6, FluidPort,   1, cmdOSC, "None" },
/*  60 */ {"AnalogApp", 0xff,   0, FluidPort,   1, RaiseApp, "None" },
/*  61 */ {"MidiSoundApp", 0xff,   1, FluidPort,   1, RaiseApp, "None" },
/*  62 */ {"LooperApp", 0xff,   2, FluidPort,   1, RaiseApp, "None" },
/*  63 */ {"LiveApp", 0xff,   4, FluidPort,   1, RaiseApp, "None" },
/*  64 */ {"MP3Player", 0xff,   5, FluidPort,   1, RaiseApp, "None" },
/*  65 */ {"TabPlayer", 0xff,   6, FluidPort,   1, RaiseApp, "None" },
/*  66 */ {"PreTab", 0xff,   0, FluidPort,   1, SwitchTab, "None" },
/*  67 */ {"ScoreTab", 0xff,   1, FluidPort,   1, SwitchTab, "None" },
/*  68 */ {"TransportApp", 0xff,   3, FluidPort,   1, RaiseApp, "None" },
/*  69 */ {"NULL", 0xff,   0, FluidPort,   1, RaiseApp, "None" },
/*  70 */ {"Switch0", 0xff,   0, FluidPort,   1, ToDesktop, "None" },
/*  71 */ {"Switch1", 0xff,   1, FluidPort,   1, ToDesktop, "None" },
/*  72 */ {"Switch2", 0xff,   2, FluidPort,   1, ToDesktop, "None" },
/*  73 */ {"Switch3", 0xff,   3, FluidPort,   1, ToDesktop, "None" },
/*  74 */ {"Switch4", 0xff,   4, FluidPort,   1, ToDesktop, "None" },
/*  75 */ {"Switch5", 0xff,   5, FluidPort,   1, ToDesktop, "None" },
/*  76 */ {"VolUp", 0xff,   5, FluidPort,   1, cmdVolume, "None" },
/*  77 */ {"VolDown", 0xff,  -5, FluidPort,   1, cmdVolume, "None" },
/*  78 */ {"RepeatA", 0xff,   0, FluidPort,   1, cmdLnTransPort, "None" },
/*  79 */ {"RepeatB", 0xff,   1, FluidPort,   1, cmdLnTransPort, "None" },
/*  80 */ {"EBuzz", SFElias,   0, FluidPort,   1, NoCustom, "None" },
/*  81 */ {"SynthB11", SFElias,   1, FluidPort,   1, NoCustom, "None" },
/*  82 */ {"KStatB", SFElias,   2, FluidPort,   1, NoCustom, "None" },
/*  83 */ {"MS20Bass", SFElias,   3, FluidPort,   1, NoCustom, "None" },
/*  84 */ {"Juno", SFElias,   4, FluidPort,   1, NoCustom, "None" },
/*  85 */ {"Moog1", SFElias,   9, FluidPort,   1, NoCustom, "None" },
/*  86 */ {"Moog2", SFElias,  10, FluidPort,   1, NoCustom, "None" },
/*  87 */ {"BassSlap", SFElias,  13, FluidPort,   1, NoCustom, "None" },
/*  88 */ {"Taurus2", SFElias,  26, FluidPort,   1, NoCustom, "None" },
/*  89 */ {"Ultimate2a", SFElias,  33, FluidPort,   1, NoCustom, "None" },
/*  90 */ {"SynthB1", SFElias,  38, FluidPort,   1, NoCustom, "None" },
/*  91 */ {"FilterBass", SFElias,  39, FluidPort,   1, NoCustom, "None" },
/*  92 */ {"BasBiy", SFElias,  45, FluidPort,   1, NoCustom, "None" },
/*  93 */ {"CZOrgan", SFElias,  51, FluidPort,   1, NoCustom, "None" },
/*  94 */ {"MoogLead1", SFElias,  53, FluidPort,   1, NoCustom, "None" },
/*  95 */ {"CZBrass4", SFElias,  64, FluidPort,   1, NoCustom, "None" },
/*  96 */ {"SinSymph", SFElias,  90, FluidPort,   1, NoCustom, "None" },
/*  97 */ {"TrigCountIn", 0xff,   4, TransportPort,   1, cmdCountIn, "LooperApp" },
/*  98 */ {"NextSong", 0xff,   2, FluidPort,   1, cmdSetList, "None" },
/*  99 */ {"PrevSong", 0xff,   1, FluidPort,   1, cmdSetList, "None" },
/* 100 */ {"Scroll", 0xff,   0, FluidPort,   1, cmdScroll, "None" },
/* 101 */ {"NextSeq", 0xff,   4, FluidPort,   1, cmdLnTransPort, "None" },
/* 102 */ {"PrevSeg", 0xff,   5, FluidPort,   1, cmdLnTransPort, "None" },
/* 103 */ {"SpeeedUp", 0xff,   6, FluidPort,   1, cmdLnTransPort, "None" },
/* 104 */ {"SlowDown", 0xff,   7, FluidPort,   1, cmdLnTransPort, "None" },
/* 105 */ {"PlPlay", 0xff,   2, FluidPort,   1, cmdLnTransPort, "None" },
/* 106 */ {"Loop Toggle", 0xff,   3, FluidPort,   1, cmdLnTransPort, "None" },
/* 107 */ {"Seek Fw", 0xff,   8, FluidPort,   1, cmdLnTransPort, "None" },
/* 108 */ {"Seek Bk", 0xff,   9, FluidPort,   1, cmdLnTransPort, "None" },
/* 109 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 110 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 111 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 112 */ {"Holds-Mel", 0xff,  21, GuitarixPort,   1, NoCustom, "NiceAhh" },
/* 113 */ {"NiceAhh", SFDSF,  90, FluidPort,   1, NoCustom, "None" },
/* 114 */ {"Holds-Hard", 0xff,  22, GuitarixPort,   1, NoCustom, "NiceAhh" },
/* 115 */ {"BetAhh", SFVintage,  63, FluidPort,   1, NoCustom, "None" },
/* 116 */ {"ToLate", SFVintage, 108, FluidPort,   1, NoCustom, "None" },
/* 117 */ {"LP All", 0xff,   1, FluidPort,   1, cmdOSC, "None" },
/* 118 */ {"LP Mute", 0xff,   7, FluidPort,   1, cmdOSC, "None" },
/* 119 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 120 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 121 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 122 */ {"BellsComp", SFDX7,  10, FluidPort,   1, NoCustom, "None" },
/* 123 */ {"Sax", SFSonidoGM,  66, FluidPort,   1, NoCustom, "None" },
/* 124 */ {"Vibra", SFVintage,  93, FluidPort,   1, NoCustom, "None" },
/* 125 */ {"Mariba1", SFDX7,  91, FluidPort,   1, NoCustom, "None" },
/* 126 */ {"Tenor", SFRolandTenor,   1, FluidPort,   1, NoCustom, "None" },
/* 127 */ {"CleanDist", 0xff,  15, GuitarixPort,   1, NoCustom, "None" },
/* 128 */ {"OctUp", 0xff,   6, GuitarixPort,   1, NoCustom, "None" },
/* 129 */ {"AutoWah", 0xff,   7, GuitarixPort,   1, NoCustom, "None" },
/* 130 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 131 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 132 */ {"Null", 0xff,   0, FluidPort,   1, MaxCommands, "None" },
/* 133 */ {"Preset1", 0xff,   1, FluidPort,   1, cmdPreset, "None" },
/* 134 */ {"Preset2", 0xff,   2, FluidPort,   1, cmdPreset, "None" },
/* 135 */ {"Preset3", 0xff,   3, FluidPort,   1, cmdPreset, "None" },
/* 136 */ {"Preset4", 0xff,   4, FluidPort,   1, cmdPreset, "None" },
/* 137 */ {"Preset5", 0xff,   5, FluidPort,   1, cmdPreset, "None" },
/* 138 */ {"Preset6", 0xff,   6, FluidPort,   1, cmdPreset, "None" },
/* 139 */ {"Midi Pre", 0xff,   0, FluidPort,   1, cmdMidiSelect, "None" },
/* 140 */ {"Slide1", 0xff,   7, GuitarixPort,   1, NoCustom, "None" },
/* 141 */ {"Slide2", 0xff,   7, FluidPort,   1, NoCustom, "None" },
},
"/home/Dropbox/FusionBlue/index.html",
6, 
 { 
"Fluid",
"Guitarix",
"Looper",
"Transport",
"Tempo",
"Click",
"Pedal"
},
{
{ "guitarix", 0 },
{ "qsynth", 0 },
{ "SooperLooper", 0 },
{ "audacity", 0 },
{ "LiveMusicApp", 0 },
{ "clementine", 0 },
{ "Tux", 0 }
},
 8, /* TempoMax  */
 0, /* Metronome On  */
 37, /* Drum down beat, midi code  */
 44, /* Drum Other beats  */
 40, /* Base Midi Note for switching  */
{ 
 	{
 "Default", 
{
/*   0 */  "Preset1", 
/*   1 */  "Preset2", 
/*   2 */  "Preset3", 
/*   3 */  "Preset4", 
/*   4 */  "Chorus", 
/*   5 */  "SatrianiComp", 
/*   6 */  "CleanDist", 
/*   7 */  "FunkyGuitar", 
/*   8 */  "PreTab", 
/*   9 */  "ScoreTab", 
/*  10 */  "MedDist", 
/*  12 */  "WahToggle", 
/*  11 */  "BetAhh", 
/*  13 */  "OctUp", 
/*  14 */  "Trumpet", 
/*  15 */  "PrevSong", 
/*  16 */  "NextSong", 
/*  17 */  "Steel Drums", 
/*  18 */  "Scroll", 
/*  19 */  "Drums", 
/*  20 */  "SinSymph", 
/*  21 */  "Moog2", 
/*  22 */  "MoogLead1", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Chorus", 
/*  25 */  "SatrianiComp", 
/*  26 */  "CleanBass", 
/*  27 */  "MedDist", 
/*  28 */  "OctBass", 
/*  29 */  "BassSlap", 
/*  30 */  "FunkBass", 
/*  31 */  "EBell", 
/*  32 */  "FunkyGuitar", 
/*  33 */  "JazzRev", 
/*  34 */  "Low Synth", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Juno", 
/*  40 */  "Moog1", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Taurus2", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
	{
 "Practice", 
{
/*   0 */  "Preset1", 
/*   1 */  "Preset2", 
/*   2 */  "Preset3", 
/*   3 */  "Chorus", 
/*   4 */  "SatrianiComp", 
/*   5 */  "FunkyGuitar", 
/*   6 */  "TransStart", 
/*   7 */  "TransCont", 
/*   8 */  "TransStop", 
/*   9 */  "TransBack", 
/*  10 */  "MidiApp", 
/*  11 */  "MP3Player", 
/*  12 */  "LP 1", 
/*  13 */  "LP 2", 
/*  14 */  "LP 3", 
/*  15 */  "LP Undo", 
/*  16 */  "LP Rec", 
/*  17 */  "LP Pause", 
/*  18 */  "Drums", 
/*  19 */  "RepeatA", 
/*  20 */  "RepeatB", 
/*  21 */  "MedDist", 
/*  22 */  "OctBass", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Piano", 
/*  25 */  "Honky", 
/*  26 */  "Breath", 
/*  27 */  "Midi Pre", 
/*  28 */  "Flute", 
/*  29 */  "Drums", 
/*  30 */  "Slap Bass", 
/*  31 */  "Marimba", 
/*  32 */  "Breath", 
/*  33 */  "Steel Drums", 
/*  34 */  "Low Synth", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Juno", 
/*  40 */  "Moog1", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Taurus2", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
	{
 "Midi", 
{
/*   0 */  "Piano", 
/*   1 */  "Honky", 
/*   2 */  "Breath", 
/*   3 */  "Organ", 
/*   4 */  "Flute", 
/*   5 */  "SynthLead", 
/*   6 */  "Trumpet", 
/*   7 */  "Steel Drums", 
/*   8 */  "Walky", 
/*   9 */  "Drums", 
/*  10 */  "Slap Bass", 
/*  11 */  "Synth Hard", 
/*  12 */  "Marimba", 
/*  13 */  "Breath1", 
/*  14 */  "Low Synth", 
/*  15 */  "EBuzz", 
/*  16 */  "SynthB11", 
/*  17 */  "KStatB", 
/*  18 */  "MS20Bass", 
/*  19 */  "Juno", 
/*  20 */  "Chorus", 
/*  21 */  "HardDist", 
/*  22 */  "CleanBass", 
/*  23 */  "MedDist", 
/*  24 */  "OctBass", 
/*  25 */  "Moog1", 
/*  26 */  "Moog2", 
/*  27 */  "Preset1", 
/*  28 */  "Preset2", 
/*  29 */  "LayoutSwitch", 
/*  30 */  "Piano", 
/*  31 */  "Honky", 
/*  32 */  "BassSlap", 
/*  33 */  "Taurus2", 
/*  34 */  "Ultimate2a", 
/*  35 */  "SynthB1", 
/*  36 */  "FilterBass", 
/*  37 */  "BasBiy", 
/*  38 */  "CZOrgan", 
/*  39 */  "MoogLead1", 
/*  40 */  "CZBrass4", 
/*  41 */  "SinSymph", 
/*  42 */  "BetAhh", 
/*  43 */  "ToLate", 
/*  44 */  "BellsComp", 
/*  45 */  "Sax", 
/*  46 */  "Vibra", 
/*  47 */  "Mariba1", 
/*  48 */  "Tenor", 
/*  49 */  "Mid Screen", 
/*  50 */  "Rak Eff6", 
/*  51 */  "Rak Eff7", 
/*  52 */  "Rak Eff8", 
/*  53 */  "Rak Eff9", 
/*  54 */  "Rak Eff10", 
/*  55 */  "Rak Eff1", 
/*  56 */  "Rak Eff2", 
/*  57 */  "Rak Eff3", 
/*  58 */  "Rak Eff4", 
/*  59 */  "Rak Eff5", 
},}, 
	{
 "Rehearsal", 
{
/*   0 */  "TransStart", 
/*   1 */  "TransCont", 
/*   2 */  "TransStop", 
/*   3 */  "TransBack", 
/*   4 */  "TransPos", 
/*   5 */  "Tap", 
/*   6 */  "Midi Tog", 
/*   7 */  "Tuner", 
/*   8 */  "AnaOnOff", 
/*   9 */  "AnaOnOff", 
/*  10 */  "LP Undo", 
/*  11 */  "LP 1", 
/*  12 */  "LP 2", 
/*  13 */  "LP 3", 
/*  14 */  "LP 4", 
/*  15 */  "LP Rec", 
/*  16 */  "LP Pause", 
/*  17 */  "LP Trig", 
/*  18 */  "LP Tap", 
/*  19 */  "LP Add", 
/*  20 */  "Chorus", 
/*  21 */  "HardDist", 
/*  22 */  "CleanBass", 
/*  23 */  "MedDist", 
/*  24 */  "OctBass", 
/*  25 */  "LayoutSwitch", 
/*  26 */  "NextSong", 
/*  27 */  "Preset1", 
/*  28 */  "Preset2", 
/*  29 */  "PrevSong", 
/*  30 */  "Piano", 
/*  31 */  "Honky", 
/*  32 */  "Breath", 
/*  33 */  "Organ", 
/*  34 */  "Flute", 
/*  35 */  "SynthLead", 
/*  36 */  "Strings", 
/*  37 */  "Trumpet", 
/*  38 */  "Steel Drums", 
/*  39 */  "Walky", 
/*  40 */  "Drums", 
/*  41 */  "Slap Bass", 
/*  42 */  "Synth Hard", 
/*  43 */  "Marimba", 
/*  44 */  "Breath", 
/*  45 */  "Steel Drums", 
/*  46 */  "Low Synth", 
/*  47 */  "Mid0", 
/*  48 */  "Mid-24", 
/*  49 */  "Mid Screen", 
/*  50 */  "NextSong", 
/*  51 */  "PrevSong", 
/*  52 */  "Rak Eff8", 
/*  53 */  "Rak Eff9", 
/*  54 */  "Rak Eff10", 
/*  55 */  "Rak Eff1", 
/*  56 */  "Rak Eff2", 
/*  57 */  "Rak Eff3", 
/*  58 */  "Rak Eff4", 
/*  59 */  "Rak Eff5", 
},}, 
	{
 "Looper", 
{
/*   0 */  "LP Rec", 
/*   1 */  "LP Trig", 
/*   2 */  "LP Pause", 
/*   3 */  "LP All", 
/*   4 */  "LP Pause All", 
/*   5 */  "LP Add", 
/*   6 */  "LooperApp", 
/*   7 */  "LiveApp", 
/*   8 */  "LP 1", 
/*   9 */  "LP 2", 
/*  10 */  "LP 3", 
/*  11 */  "LP 4", 
/*  12 */  "LP All", 
/*  13 */  "TrigCountIn", 
/*  14 */  "LP Undo", 
/*  15 */  "LP Tap", 
/*  16 */  "LP Mute", 
/*  17 */  "LP Undo", 
/*  18 */  "LP Rec", 
/*  19 */  "LP Pause", 
/*  20 */  "EBuzz", 
/*  21 */  "LP Mute", 
/*  22 */  "OctBass", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Piano", 
/*  25 */  "Honky", 
/*  26 */  "Breath", 
/*  27 */  "Midi Pre", 
/*  28 */  "Flute", 
/*  29 */  "Drums", 
/*  30 */  "Slap Bass", 
/*  31 */  "Marimba", 
/*  32 */  "Breath", 
/*  33 */  "Steel Drums", 
/*  34 */  "Low Synth", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Juno", 
/*  40 */  "Moog1", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Taurus2", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
	{
 "Bass", 
{
/*   0 */  "Preset1", 
/*   1 */  "Preset2", 
/*   2 */  "Preset3", 
/*   3 */  "Chorus", 
/*   4 */  "OctBass", 
/*   5 */  "CleanBass", 
/*   6 */  "FunkBass", 
/*   7 */  "FunkyGuitar", 
/*   8 */  "Breath", 
/*   9 */  "Flute", 
/*  10 */  "MS20Bass", 
/*  11 */  "SatrianiComp", 
/*  12 */  "LP 1", 
/*  13 */  "LP 2", 
/*  14 */  "LP 3", 
/*  15 */  "LP Undo", 
/*  16 */  "LP Rec", 
/*  17 */  "LP Pause", 
/*  18 */  "Drums", 
/*  19 */  "Flute", 
/*  20 */  "SatrianiComp", 
/*  21 */  "MedDist", 
/*  22 */  "OctBass", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Piano", 
/*  25 */  "Honky", 
/*  26 */  "Breath", 
/*  27 */  "Midi Pre", 
/*  28 */  "Flute", 
/*  29 */  "Drums", 
/*  30 */  "Slap Bass", 
/*  31 */  "Marimba", 
/*  32 */  "Breath", 
/*  33 */  "Steel Drums", 
/*  34 */  "Low Synth", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Juno", 
/*  40 */  "Moog1", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Taurus2", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
	{
 "Guitar", 
{
/*   0 */  "Preset1", 
/*   1 */  "Preset2", 
/*   2 */  "Preset3", 
/*   3 */  "Chorus", 
/*   4 */  "SatrianiComp", 
/*   5 */  "FunkyGuitar", 
/*   6 */  "CleanDist", 
/*   7 */  "MedDist", 
/*   8 */  "Breath", 
/*   9 */  "Flute", 
/*  10 */  "SynthLead", 
/*  11 */  "EBell", 
/*  12 */  "Tenor", 
/*  13 */  "Strings", 
/*  14 */  "Vibra", 
/*  15 */  "Sax", 
/*  16 */  "AnalogApp", 
/*  17 */  "LiveApp", 
/*  18 */  "ToLate", 
/*  19 */  "Flute", 
/*  20 */  "Walky", 
/*  21 */  "MedDist", 
/*  22 */  "OctBass", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Piano", 
/*  25 */  "Holds-Mel", 
/*  26 */  "Holds-Hard", 
/*  27 */  "Midi Pre", 
/*  28 */  "Flute", 
/*  29 */  "Drums", 
/*  30 */  "Slap Bass", 
/*  31 */  "Marimba", 
/*  32 */  "Breath", 
/*  33 */  "Steel Drums", 
/*  34 */  "BellsComp", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Sax", 
/*  40 */  "Vibra", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Mariba1", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
	{
 "Transcribe", 
{
/*   0 */  "Preset1", 
/*   1 */  "Preset2", 
/*   2 */  "Preset3", 
/*   3 */  "Chorus", 
/*   4 */  "NextSeq", 
/*   5 */  "PrevSeg", 
/*   6 */  "RepeatA", 
/*   7 */  "RepeatB", 
/*   8 */  "Loop Toggle", 
/*   9 */  "PlPlay", 
/*  10 */  "SpeeedUp", 
/*  11 */  "SlowDown", 
/*  12 */  "Seek Fw", 
/*  13 */  "Seek Bk", 
/*  14 */  "LP 3", 
/*  15 */  "LP Undo", 
/*  16 */  "LP Rec", 
/*  17 */  "LP Pause", 
/*  18 */  "Drums", 
/*  19 */  "Flute", 
/*  20 */  "SatrianiComp", 
/*  21 */  "MedDist", 
/*  22 */  "OctBass", 
/*  23 */  "LayoutSwitch", 
/*  24 */  "Piano", 
/*  25 */  "Honky", 
/*  26 */  "Breath", 
/*  27 */  "Midi Pre", 
/*  28 */  "Flute", 
/*  29 */  "Drums", 
/*  30 */  "Slap Bass", 
/*  31 */  "Marimba", 
/*  32 */  "Breath", 
/*  33 */  "Steel Drums", 
/*  34 */  "Low Synth", 
/*  35 */  "EBuzz", 
/*  36 */  "SynthB11", 
/*  37 */  "KStatB", 
/*  38 */  "MS20Bass", 
/*  39 */  "Juno", 
/*  40 */  "Moog1", 
/*  41 */  "Moog2", 
/*  42 */  "BassSlap", 
/*  43 */  "Taurus2", 
/*  44 */  "Ultimate2a", 
/*  45 */  "SynthB1", 
/*  46 */  "FilterBass", 
/*  47 */  "CZOrgan", 
/*  48 */  "MoogLead1", 
/*  49 */  "CZBrass4", 
/*  50 */  "SinSymph", 
/*  51 */  "Rak Eff1", 
/*  52 */  "Rak Eff2", 
/*  53 */  "Rak Eff3", 
},}, 
{
 "", { },	},
 },
}; 
