# Makefile.in generated by automake 1.16.5 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2021 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.





am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/livemusicapp
pkgincludedir = $(includedir)/livemusicapp
pkglibdir = $(libdir)/livemusicapp
pkglibexecdir = $(libexecdir)/livemusicapp
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
bin_PROGRAMS = LiveMusicApp$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/src/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(Prefsdir)" \
	"$(DESTDIR)$(Songsdir)" "$(DESTDIR)$(Tune1dir)"
PROGRAMS = $(bin_PROGRAMS)
am_LiveMusicApp_OBJECTS = LiveMusicApp-AlsaUtils.$(OBJEXT) \
	LiveMusicApp-HTML.$(OBJEXT) LiveMusicApp-PrefsFile.$(OBJEXT) \
	LiveMusicApp-Timers.$(OBJEXT) LiveMusicApp-Chorder.$(OBJEXT) \
	LiveMusicApp-LiveMusicApp.$(OBJEXT) \
	LiveMusicApp-PrefsGui.$(OBJEXT) \
	LiveMusicApp-transport.$(OBJEXT) \
	LiveMusicApp-Connections.$(OBJEXT) \
	LiveMusicApp-MyWidgets.$(OBJEXT) \
	LiveMusicApp-RightMenuClick.$(OBJEXT) \
	LiveMusicApp-wmctrl.$(OBJEXT) LiveMusicApp-HIDGrab.$(OBJEXT) \
	LiveMusicApp-Player.$(OBJEXT) LiveMusicApp-SooperOSC.$(OBJEXT) \
	LiveMusicApp-APlayMidi.$(OBJEXT)
LiveMusicApp_OBJECTS = $(am_LiveMusicApp_OBJECTS)
LiveMusicApp_LDADD = $(LDADD)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
LiveMusicApp_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(LiveMusicApp_CFLAGS) \
	$(CFLAGS) $(LiveMusicApp_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)/src
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/LiveMusicApp-APlayMidi.Po \
	./$(DEPDIR)/LiveMusicApp-AlsaUtils.Po \
	./$(DEPDIR)/LiveMusicApp-Chorder.Po \
	./$(DEPDIR)/LiveMusicApp-Connections.Po \
	./$(DEPDIR)/LiveMusicApp-HIDGrab.Po \
	./$(DEPDIR)/LiveMusicApp-HTML.Po \
	./$(DEPDIR)/LiveMusicApp-LiveMusicApp.Po \
	./$(DEPDIR)/LiveMusicApp-MyWidgets.Po \
	./$(DEPDIR)/LiveMusicApp-Player.Po \
	./$(DEPDIR)/LiveMusicApp-PrefsFile.Po \
	./$(DEPDIR)/LiveMusicApp-PrefsGui.Po \
	./$(DEPDIR)/LiveMusicApp-RightMenuClick.Po \
	./$(DEPDIR)/LiveMusicApp-SooperOSC.Po \
	./$(DEPDIR)/LiveMusicApp-Timers.Po \
	./$(DEPDIR)/LiveMusicApp-transport.Po \
	./$(DEPDIR)/LiveMusicApp-wmctrl.Po
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(LiveMusicApp_SOURCES)
DIST_SOURCES = $(LiveMusicApp_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
DATA = $(Prefs_DATA) $(Songs_DATA) $(Tune1_DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/src/config.h.in \
	AUTHORS COPYING ChangeLog INSTALL NEWS README compile \
	config.guess config.sub depcomp install-sh ltmain.sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
# Exists only to be overridden by the user if desired.
AM_DISTCHECK_DVI_TARGET = dvi
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} '/home/elias/workspace/LiveMusicApp/missing' aclocal-1.16
ALLOCA = 
ALSA_CFLAGS = 
ALSA_LIBS = -lasound
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} '/home/elias/workspace/LiveMusicApp/missing' autoconf
AUTOHEADER = ${SHELL} '/home/elias/workspace/LiveMusicApp/missing' autoheader
AUTOMAKE = ${SHELL} '/home/elias/workspace/LiveMusicApp/missing' automake-1.16
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -fdiagnostics-color=always
CPP = gcc -E
CPPFLAGS = -fdiagnostics-color=always
CSCOPE = cscope
CTAGS = ctags
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/local/bin/grep -E
ETAGS = etags
EXEEXT = 
FGREP = /usr/local/bin/grep -F
GLADEUI_CFLAGS = -pthread -I/usr/include/libgladeui-2.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GLADEUI_LIBS = -lgladeui-2 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
GREP = /usr/local/bin/grep
GTK3_CFLAGS = -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GTK3_LIBS = -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
INSTALL = /usr/local/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JACK_CFLAGS = -I/usr/local/include
JACK_LIBS = -L/usr/local/lib -ljack
LD = /usr/local/bin/ld -m elf_x86_64
LDFLAGS = 
LIBLO_CFLAGS = -I/usr/local/include
LIBLO_LIBS = -L/usr/local/lib -llo -lpthread
LIBOBJS = 
LIBS = -lpthread -lxmltok -lrt -lm -lXmu -lX11 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} '/home/elias/workspace/LiveMusicApp/missing' makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/local/bin/mkdir -p
NM = /usr/local/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = livemusicapp
PACKAGE_BUGREPORT = elias@kesh.com
PACKAGE_NAME = LiveMusicApp
PACKAGE_STRING = LiveMusicApp 2.1.6
PACKAGE_TARNAME = livemusicapp
PACKAGE_URL = 
PACKAGE_VERSION = 2.1.6
PATH_SEPARATOR = :
PKG_CONFIG = /usr/local/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /usr/lib/pkgconfig:/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig
RANLIB = ranlib
SED = /usr/local/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 2.1.6
WEBKIT2GTK_CFLAGS = -pthread -I/usr/local/include/libxml2 -I/usr/include/webkitgtk-4.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libsoup-2.4 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
WEBKIT2GTK_LIBS = -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgio-2.0 -ljavascriptcoregtk-4.0 -lgobject-2.0 -lglib-2.0
XMKMF = 
abs_builddir = /home/elias/workspace/LiveMusicApp
abs_srcdir = /home/elias/workspace/LiveMusicApp
abs_top_builddir = /home/elias/workspace/LiveMusicApp
abs_top_srcdir = /home/elias/workspace/LiveMusicApp
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/elias/workspace/LiveMusicApp/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
LiveMusicApp_SOURCES = src/AlsaUtils.c \
src/HTML.c \
src/PrefsFile.c \
src/Timers.c \
src/Chorder.c \
src/LiveMusicApp.c \
src/PrefsGui.c \
src/transport.c \
src/Connections.c \
src/MyWidgets.c \
src/RightMenuClick.c \
src/wmctrl.c \
src/HIDGrab.c \
src/Player.c \
src/SooperOSC.c \
src/APlayMidi.c \
src/aconfig.h \
src/DefPrefs.h \
src/LiveMusicApp.h \
src/PrefsFile.h \
src/Timers.h \
src/AlsaUtils.h \
src/GenPrefs.h \
src/MyWidgets.h \
src/PrefsGui.h \
src/Connections.h \
src/HTML.h \
src/Player.h \
src/APlayMidi.h \
src/SooperOSC.h 

LiveMusicApp_CPPFLAGS = -Wno-incompatible-pointer-types -Wformat=0 \
	-Wno-unused-result -Wno-deprecated -Wdeprecated-declarations \
	-Wpointer-to-int-cast -Wno-int-to-pointer-cast $(GTK4_CFLAGS) \
	$(ALSA_CFLAGS) $(GLADEUI_CFLAGS) $(WEBKIT2GTK_CFLAGS) \
	$(JACK_CFLAGS) $(LIBLO_CFLAGS) -DMY_BUILD_NUMBER=$$(cat \
	./Scripts/BuildNumber) -DMY_VERSION_NUMBER=$$(cat \
	./Scripts/version.txt)
#LiveMusicApp_CPPFLAGS += -DBUILD_NUMBER1=$(shell ./IncBuildNumber.sh)
LiveMusicApp_CFLAGS = $(LiveMusicApp_CPPFLAGS)
LiveMusicApp_LDFLAGS = -L/usr/lib/x86_64-linux-gnu/ -lxmltok -lxml2 \
	$(GTK4_LIBS) $(ALSA_LIBS) $(GLADEUI_v) $(WEBKIT2GTK_LIBS) \
	$(JACK_LIBS) $(LIBLO_LIBS) -Xlinker --defsym -Xlinker \
	__Bump_NUMBER=$$(./Scripts/IncBuildNumber.sh)
# LiveMusicApp_LDFLAGS += -Xlinker --defsym -Xlinker __BUILD_DATE=$$(date +'%Y%m%d')

# Copy the preferences.
#Prefsdir = "$(HOME)/.config/LiveMusicApp/"
# Prefs_DATA = LiveMusicRes/* 
# Prefs_DATA = LiveMusicRes/* -c -m 644
Prefsdir = "$(prefix)/share/LiveMusicApp/"
Prefs_DATA = LiveMusicRes/*
Songsdir = "$(prefix)/share/LiveMusicApp/MySongs/"
Songs_DATA = MySongs/background.png \
		MySongs/logo.jpg \
		MySongs/index.html \
		MySongs/LiveMusicAppDocumentation.pdf

Tune1dir = "$(prefix)/share/LiveMusicApp/MySongs/BlueRondo"
Tune1_DATA = MySongs/BlueRondo/*
all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

src/config.h: src/stamp-h1
	@test -f $@ || rm -f src/stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) src/stamp-h1

src/stamp-h1: $(top_srcdir)/src/config.h.in $(top_builddir)/config.status
	@rm -f src/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status src/config.h
$(top_srcdir)/src/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f src/stamp-h1
	touch $@

distclean-hdr:
	-rm -f src/config.h src/stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

LiveMusicApp$(EXEEXT): $(LiveMusicApp_OBJECTS) $(LiveMusicApp_DEPENDENCIES) $(EXTRA_LiveMusicApp_DEPENDENCIES) 
	@rm -f LiveMusicApp$(EXEEXT)
	$(AM_V_CCLD)$(LiveMusicApp_LINK) $(LiveMusicApp_OBJECTS) $(LiveMusicApp_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/LiveMusicApp-APlayMidi.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-AlsaUtils.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-Chorder.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-Connections.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-HIDGrab.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-HTML.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-LiveMusicApp.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-MyWidgets.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-Player.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-PrefsFile.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-PrefsGui.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-RightMenuClick.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-SooperOSC.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-Timers.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-transport.Po # am--include-marker
include ./$(DEPDIR)/LiveMusicApp-wmctrl.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

LiveMusicApp-AlsaUtils.o: src/AlsaUtils.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-AlsaUtils.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-AlsaUtils.Tpo -c -o LiveMusicApp-AlsaUtils.o `test -f 'src/AlsaUtils.c' || echo '$(srcdir)/'`src/AlsaUtils.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-AlsaUtils.Tpo $(DEPDIR)/LiveMusicApp-AlsaUtils.Po
#	$(AM_V_CC)source='src/AlsaUtils.c' object='LiveMusicApp-AlsaUtils.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-AlsaUtils.o `test -f 'src/AlsaUtils.c' || echo '$(srcdir)/'`src/AlsaUtils.c

LiveMusicApp-AlsaUtils.obj: src/AlsaUtils.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-AlsaUtils.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-AlsaUtils.Tpo -c -o LiveMusicApp-AlsaUtils.obj `if test -f 'src/AlsaUtils.c'; then $(CYGPATH_W) 'src/AlsaUtils.c'; else $(CYGPATH_W) '$(srcdir)/src/AlsaUtils.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-AlsaUtils.Tpo $(DEPDIR)/LiveMusicApp-AlsaUtils.Po
#	$(AM_V_CC)source='src/AlsaUtils.c' object='LiveMusicApp-AlsaUtils.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-AlsaUtils.obj `if test -f 'src/AlsaUtils.c'; then $(CYGPATH_W) 'src/AlsaUtils.c'; else $(CYGPATH_W) '$(srcdir)/src/AlsaUtils.c'; fi`

LiveMusicApp-HTML.o: src/HTML.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-HTML.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-HTML.Tpo -c -o LiveMusicApp-HTML.o `test -f 'src/HTML.c' || echo '$(srcdir)/'`src/HTML.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-HTML.Tpo $(DEPDIR)/LiveMusicApp-HTML.Po
#	$(AM_V_CC)source='src/HTML.c' object='LiveMusicApp-HTML.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-HTML.o `test -f 'src/HTML.c' || echo '$(srcdir)/'`src/HTML.c

LiveMusicApp-HTML.obj: src/HTML.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-HTML.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-HTML.Tpo -c -o LiveMusicApp-HTML.obj `if test -f 'src/HTML.c'; then $(CYGPATH_W) 'src/HTML.c'; else $(CYGPATH_W) '$(srcdir)/src/HTML.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-HTML.Tpo $(DEPDIR)/LiveMusicApp-HTML.Po
#	$(AM_V_CC)source='src/HTML.c' object='LiveMusicApp-HTML.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-HTML.obj `if test -f 'src/HTML.c'; then $(CYGPATH_W) 'src/HTML.c'; else $(CYGPATH_W) '$(srcdir)/src/HTML.c'; fi`

LiveMusicApp-PrefsFile.o: src/PrefsFile.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-PrefsFile.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-PrefsFile.Tpo -c -o LiveMusicApp-PrefsFile.o `test -f 'src/PrefsFile.c' || echo '$(srcdir)/'`src/PrefsFile.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-PrefsFile.Tpo $(DEPDIR)/LiveMusicApp-PrefsFile.Po
#	$(AM_V_CC)source='src/PrefsFile.c' object='LiveMusicApp-PrefsFile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-PrefsFile.o `test -f 'src/PrefsFile.c' || echo '$(srcdir)/'`src/PrefsFile.c

LiveMusicApp-PrefsFile.obj: src/PrefsFile.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-PrefsFile.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-PrefsFile.Tpo -c -o LiveMusicApp-PrefsFile.obj `if test -f 'src/PrefsFile.c'; then $(CYGPATH_W) 'src/PrefsFile.c'; else $(CYGPATH_W) '$(srcdir)/src/PrefsFile.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-PrefsFile.Tpo $(DEPDIR)/LiveMusicApp-PrefsFile.Po
#	$(AM_V_CC)source='src/PrefsFile.c' object='LiveMusicApp-PrefsFile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-PrefsFile.obj `if test -f 'src/PrefsFile.c'; then $(CYGPATH_W) 'src/PrefsFile.c'; else $(CYGPATH_W) '$(srcdir)/src/PrefsFile.c'; fi`

LiveMusicApp-Timers.o: src/Timers.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Timers.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-Timers.Tpo -c -o LiveMusicApp-Timers.o `test -f 'src/Timers.c' || echo '$(srcdir)/'`src/Timers.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Timers.Tpo $(DEPDIR)/LiveMusicApp-Timers.Po
#	$(AM_V_CC)source='src/Timers.c' object='LiveMusicApp-Timers.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Timers.o `test -f 'src/Timers.c' || echo '$(srcdir)/'`src/Timers.c

LiveMusicApp-Timers.obj: src/Timers.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Timers.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-Timers.Tpo -c -o LiveMusicApp-Timers.obj `if test -f 'src/Timers.c'; then $(CYGPATH_W) 'src/Timers.c'; else $(CYGPATH_W) '$(srcdir)/src/Timers.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Timers.Tpo $(DEPDIR)/LiveMusicApp-Timers.Po
#	$(AM_V_CC)source='src/Timers.c' object='LiveMusicApp-Timers.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Timers.obj `if test -f 'src/Timers.c'; then $(CYGPATH_W) 'src/Timers.c'; else $(CYGPATH_W) '$(srcdir)/src/Timers.c'; fi`

LiveMusicApp-Chorder.o: src/Chorder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Chorder.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-Chorder.Tpo -c -o LiveMusicApp-Chorder.o `test -f 'src/Chorder.c' || echo '$(srcdir)/'`src/Chorder.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Chorder.Tpo $(DEPDIR)/LiveMusicApp-Chorder.Po
#	$(AM_V_CC)source='src/Chorder.c' object='LiveMusicApp-Chorder.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Chorder.o `test -f 'src/Chorder.c' || echo '$(srcdir)/'`src/Chorder.c

LiveMusicApp-Chorder.obj: src/Chorder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Chorder.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-Chorder.Tpo -c -o LiveMusicApp-Chorder.obj `if test -f 'src/Chorder.c'; then $(CYGPATH_W) 'src/Chorder.c'; else $(CYGPATH_W) '$(srcdir)/src/Chorder.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Chorder.Tpo $(DEPDIR)/LiveMusicApp-Chorder.Po
#	$(AM_V_CC)source='src/Chorder.c' object='LiveMusicApp-Chorder.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Chorder.obj `if test -f 'src/Chorder.c'; then $(CYGPATH_W) 'src/Chorder.c'; else $(CYGPATH_W) '$(srcdir)/src/Chorder.c'; fi`

LiveMusicApp-LiveMusicApp.o: src/LiveMusicApp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-LiveMusicApp.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-LiveMusicApp.Tpo -c -o LiveMusicApp-LiveMusicApp.o `test -f 'src/LiveMusicApp.c' || echo '$(srcdir)/'`src/LiveMusicApp.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-LiveMusicApp.Tpo $(DEPDIR)/LiveMusicApp-LiveMusicApp.Po
#	$(AM_V_CC)source='src/LiveMusicApp.c' object='LiveMusicApp-LiveMusicApp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-LiveMusicApp.o `test -f 'src/LiveMusicApp.c' || echo '$(srcdir)/'`src/LiveMusicApp.c

LiveMusicApp-LiveMusicApp.obj: src/LiveMusicApp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-LiveMusicApp.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-LiveMusicApp.Tpo -c -o LiveMusicApp-LiveMusicApp.obj `if test -f 'src/LiveMusicApp.c'; then $(CYGPATH_W) 'src/LiveMusicApp.c'; else $(CYGPATH_W) '$(srcdir)/src/LiveMusicApp.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-LiveMusicApp.Tpo $(DEPDIR)/LiveMusicApp-LiveMusicApp.Po
#	$(AM_V_CC)source='src/LiveMusicApp.c' object='LiveMusicApp-LiveMusicApp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-LiveMusicApp.obj `if test -f 'src/LiveMusicApp.c'; then $(CYGPATH_W) 'src/LiveMusicApp.c'; else $(CYGPATH_W) '$(srcdir)/src/LiveMusicApp.c'; fi`

LiveMusicApp-PrefsGui.o: src/PrefsGui.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-PrefsGui.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-PrefsGui.Tpo -c -o LiveMusicApp-PrefsGui.o `test -f 'src/PrefsGui.c' || echo '$(srcdir)/'`src/PrefsGui.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-PrefsGui.Tpo $(DEPDIR)/LiveMusicApp-PrefsGui.Po
#	$(AM_V_CC)source='src/PrefsGui.c' object='LiveMusicApp-PrefsGui.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-PrefsGui.o `test -f 'src/PrefsGui.c' || echo '$(srcdir)/'`src/PrefsGui.c

LiveMusicApp-PrefsGui.obj: src/PrefsGui.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-PrefsGui.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-PrefsGui.Tpo -c -o LiveMusicApp-PrefsGui.obj `if test -f 'src/PrefsGui.c'; then $(CYGPATH_W) 'src/PrefsGui.c'; else $(CYGPATH_W) '$(srcdir)/src/PrefsGui.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-PrefsGui.Tpo $(DEPDIR)/LiveMusicApp-PrefsGui.Po
#	$(AM_V_CC)source='src/PrefsGui.c' object='LiveMusicApp-PrefsGui.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-PrefsGui.obj `if test -f 'src/PrefsGui.c'; then $(CYGPATH_W) 'src/PrefsGui.c'; else $(CYGPATH_W) '$(srcdir)/src/PrefsGui.c'; fi`

LiveMusicApp-transport.o: src/transport.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-transport.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-transport.Tpo -c -o LiveMusicApp-transport.o `test -f 'src/transport.c' || echo '$(srcdir)/'`src/transport.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-transport.Tpo $(DEPDIR)/LiveMusicApp-transport.Po
#	$(AM_V_CC)source='src/transport.c' object='LiveMusicApp-transport.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-transport.o `test -f 'src/transport.c' || echo '$(srcdir)/'`src/transport.c

LiveMusicApp-transport.obj: src/transport.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-transport.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-transport.Tpo -c -o LiveMusicApp-transport.obj `if test -f 'src/transport.c'; then $(CYGPATH_W) 'src/transport.c'; else $(CYGPATH_W) '$(srcdir)/src/transport.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-transport.Tpo $(DEPDIR)/LiveMusicApp-transport.Po
#	$(AM_V_CC)source='src/transport.c' object='LiveMusicApp-transport.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-transport.obj `if test -f 'src/transport.c'; then $(CYGPATH_W) 'src/transport.c'; else $(CYGPATH_W) '$(srcdir)/src/transport.c'; fi`

LiveMusicApp-Connections.o: src/Connections.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Connections.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-Connections.Tpo -c -o LiveMusicApp-Connections.o `test -f 'src/Connections.c' || echo '$(srcdir)/'`src/Connections.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Connections.Tpo $(DEPDIR)/LiveMusicApp-Connections.Po
#	$(AM_V_CC)source='src/Connections.c' object='LiveMusicApp-Connections.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Connections.o `test -f 'src/Connections.c' || echo '$(srcdir)/'`src/Connections.c

LiveMusicApp-Connections.obj: src/Connections.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Connections.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-Connections.Tpo -c -o LiveMusicApp-Connections.obj `if test -f 'src/Connections.c'; then $(CYGPATH_W) 'src/Connections.c'; else $(CYGPATH_W) '$(srcdir)/src/Connections.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Connections.Tpo $(DEPDIR)/LiveMusicApp-Connections.Po
#	$(AM_V_CC)source='src/Connections.c' object='LiveMusicApp-Connections.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Connections.obj `if test -f 'src/Connections.c'; then $(CYGPATH_W) 'src/Connections.c'; else $(CYGPATH_W) '$(srcdir)/src/Connections.c'; fi`

LiveMusicApp-MyWidgets.o: src/MyWidgets.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-MyWidgets.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-MyWidgets.Tpo -c -o LiveMusicApp-MyWidgets.o `test -f 'src/MyWidgets.c' || echo '$(srcdir)/'`src/MyWidgets.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-MyWidgets.Tpo $(DEPDIR)/LiveMusicApp-MyWidgets.Po
#	$(AM_V_CC)source='src/MyWidgets.c' object='LiveMusicApp-MyWidgets.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-MyWidgets.o `test -f 'src/MyWidgets.c' || echo '$(srcdir)/'`src/MyWidgets.c

LiveMusicApp-MyWidgets.obj: src/MyWidgets.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-MyWidgets.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-MyWidgets.Tpo -c -o LiveMusicApp-MyWidgets.obj `if test -f 'src/MyWidgets.c'; then $(CYGPATH_W) 'src/MyWidgets.c'; else $(CYGPATH_W) '$(srcdir)/src/MyWidgets.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-MyWidgets.Tpo $(DEPDIR)/LiveMusicApp-MyWidgets.Po
#	$(AM_V_CC)source='src/MyWidgets.c' object='LiveMusicApp-MyWidgets.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-MyWidgets.obj `if test -f 'src/MyWidgets.c'; then $(CYGPATH_W) 'src/MyWidgets.c'; else $(CYGPATH_W) '$(srcdir)/src/MyWidgets.c'; fi`

LiveMusicApp-RightMenuClick.o: src/RightMenuClick.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-RightMenuClick.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-RightMenuClick.Tpo -c -o LiveMusicApp-RightMenuClick.o `test -f 'src/RightMenuClick.c' || echo '$(srcdir)/'`src/RightMenuClick.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-RightMenuClick.Tpo $(DEPDIR)/LiveMusicApp-RightMenuClick.Po
#	$(AM_V_CC)source='src/RightMenuClick.c' object='LiveMusicApp-RightMenuClick.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-RightMenuClick.o `test -f 'src/RightMenuClick.c' || echo '$(srcdir)/'`src/RightMenuClick.c

LiveMusicApp-RightMenuClick.obj: src/RightMenuClick.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-RightMenuClick.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-RightMenuClick.Tpo -c -o LiveMusicApp-RightMenuClick.obj `if test -f 'src/RightMenuClick.c'; then $(CYGPATH_W) 'src/RightMenuClick.c'; else $(CYGPATH_W) '$(srcdir)/src/RightMenuClick.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-RightMenuClick.Tpo $(DEPDIR)/LiveMusicApp-RightMenuClick.Po
#	$(AM_V_CC)source='src/RightMenuClick.c' object='LiveMusicApp-RightMenuClick.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-RightMenuClick.obj `if test -f 'src/RightMenuClick.c'; then $(CYGPATH_W) 'src/RightMenuClick.c'; else $(CYGPATH_W) '$(srcdir)/src/RightMenuClick.c'; fi`

LiveMusicApp-wmctrl.o: src/wmctrl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-wmctrl.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-wmctrl.Tpo -c -o LiveMusicApp-wmctrl.o `test -f 'src/wmctrl.c' || echo '$(srcdir)/'`src/wmctrl.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-wmctrl.Tpo $(DEPDIR)/LiveMusicApp-wmctrl.Po
#	$(AM_V_CC)source='src/wmctrl.c' object='LiveMusicApp-wmctrl.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-wmctrl.o `test -f 'src/wmctrl.c' || echo '$(srcdir)/'`src/wmctrl.c

LiveMusicApp-wmctrl.obj: src/wmctrl.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-wmctrl.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-wmctrl.Tpo -c -o LiveMusicApp-wmctrl.obj `if test -f 'src/wmctrl.c'; then $(CYGPATH_W) 'src/wmctrl.c'; else $(CYGPATH_W) '$(srcdir)/src/wmctrl.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-wmctrl.Tpo $(DEPDIR)/LiveMusicApp-wmctrl.Po
#	$(AM_V_CC)source='src/wmctrl.c' object='LiveMusicApp-wmctrl.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-wmctrl.obj `if test -f 'src/wmctrl.c'; then $(CYGPATH_W) 'src/wmctrl.c'; else $(CYGPATH_W) '$(srcdir)/src/wmctrl.c'; fi`

LiveMusicApp-HIDGrab.o: src/HIDGrab.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-HIDGrab.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-HIDGrab.Tpo -c -o LiveMusicApp-HIDGrab.o `test -f 'src/HIDGrab.c' || echo '$(srcdir)/'`src/HIDGrab.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-HIDGrab.Tpo $(DEPDIR)/LiveMusicApp-HIDGrab.Po
#	$(AM_V_CC)source='src/HIDGrab.c' object='LiveMusicApp-HIDGrab.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-HIDGrab.o `test -f 'src/HIDGrab.c' || echo '$(srcdir)/'`src/HIDGrab.c

LiveMusicApp-HIDGrab.obj: src/HIDGrab.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-HIDGrab.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-HIDGrab.Tpo -c -o LiveMusicApp-HIDGrab.obj `if test -f 'src/HIDGrab.c'; then $(CYGPATH_W) 'src/HIDGrab.c'; else $(CYGPATH_W) '$(srcdir)/src/HIDGrab.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-HIDGrab.Tpo $(DEPDIR)/LiveMusicApp-HIDGrab.Po
#	$(AM_V_CC)source='src/HIDGrab.c' object='LiveMusicApp-HIDGrab.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-HIDGrab.obj `if test -f 'src/HIDGrab.c'; then $(CYGPATH_W) 'src/HIDGrab.c'; else $(CYGPATH_W) '$(srcdir)/src/HIDGrab.c'; fi`

LiveMusicApp-Player.o: src/Player.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Player.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-Player.Tpo -c -o LiveMusicApp-Player.o `test -f 'src/Player.c' || echo '$(srcdir)/'`src/Player.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Player.Tpo $(DEPDIR)/LiveMusicApp-Player.Po
#	$(AM_V_CC)source='src/Player.c' object='LiveMusicApp-Player.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Player.o `test -f 'src/Player.c' || echo '$(srcdir)/'`src/Player.c

LiveMusicApp-Player.obj: src/Player.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-Player.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-Player.Tpo -c -o LiveMusicApp-Player.obj `if test -f 'src/Player.c'; then $(CYGPATH_W) 'src/Player.c'; else $(CYGPATH_W) '$(srcdir)/src/Player.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-Player.Tpo $(DEPDIR)/LiveMusicApp-Player.Po
#	$(AM_V_CC)source='src/Player.c' object='LiveMusicApp-Player.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-Player.obj `if test -f 'src/Player.c'; then $(CYGPATH_W) 'src/Player.c'; else $(CYGPATH_W) '$(srcdir)/src/Player.c'; fi`

LiveMusicApp-SooperOSC.o: src/SooperOSC.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-SooperOSC.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-SooperOSC.Tpo -c -o LiveMusicApp-SooperOSC.o `test -f 'src/SooperOSC.c' || echo '$(srcdir)/'`src/SooperOSC.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-SooperOSC.Tpo $(DEPDIR)/LiveMusicApp-SooperOSC.Po
#	$(AM_V_CC)source='src/SooperOSC.c' object='LiveMusicApp-SooperOSC.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-SooperOSC.o `test -f 'src/SooperOSC.c' || echo '$(srcdir)/'`src/SooperOSC.c

LiveMusicApp-SooperOSC.obj: src/SooperOSC.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-SooperOSC.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-SooperOSC.Tpo -c -o LiveMusicApp-SooperOSC.obj `if test -f 'src/SooperOSC.c'; then $(CYGPATH_W) 'src/SooperOSC.c'; else $(CYGPATH_W) '$(srcdir)/src/SooperOSC.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-SooperOSC.Tpo $(DEPDIR)/LiveMusicApp-SooperOSC.Po
#	$(AM_V_CC)source='src/SooperOSC.c' object='LiveMusicApp-SooperOSC.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-SooperOSC.obj `if test -f 'src/SooperOSC.c'; then $(CYGPATH_W) 'src/SooperOSC.c'; else $(CYGPATH_W) '$(srcdir)/src/SooperOSC.c'; fi`

LiveMusicApp-APlayMidi.o: src/APlayMidi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-APlayMidi.o -MD -MP -MF $(DEPDIR)/LiveMusicApp-APlayMidi.Tpo -c -o LiveMusicApp-APlayMidi.o `test -f 'src/APlayMidi.c' || echo '$(srcdir)/'`src/APlayMidi.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-APlayMidi.Tpo $(DEPDIR)/LiveMusicApp-APlayMidi.Po
#	$(AM_V_CC)source='src/APlayMidi.c' object='LiveMusicApp-APlayMidi.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-APlayMidi.o `test -f 'src/APlayMidi.c' || echo '$(srcdir)/'`src/APlayMidi.c

LiveMusicApp-APlayMidi.obj: src/APlayMidi.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -MT LiveMusicApp-APlayMidi.obj -MD -MP -MF $(DEPDIR)/LiveMusicApp-APlayMidi.Tpo -c -o LiveMusicApp-APlayMidi.obj `if test -f 'src/APlayMidi.c'; then $(CYGPATH_W) 'src/APlayMidi.c'; else $(CYGPATH_W) '$(srcdir)/src/APlayMidi.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/LiveMusicApp-APlayMidi.Tpo $(DEPDIR)/LiveMusicApp-APlayMidi.Po
#	$(AM_V_CC)source='src/APlayMidi.c' object='LiveMusicApp-APlayMidi.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(LiveMusicApp_CPPFLAGS) $(CPPFLAGS) $(LiveMusicApp_CFLAGS) $(CFLAGS) -c -o LiveMusicApp-APlayMidi.obj `if test -f 'src/APlayMidi.c'; then $(CYGPATH_W) 'src/APlayMidi.c'; else $(CYGPATH_W) '$(srcdir)/src/APlayMidi.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt
install-PrefsDATA: $(Prefs_DATA)
	@$(NORMAL_INSTALL)
	@list='$(Prefs_DATA)'; test -n "$(Prefsdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(Prefsdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(Prefsdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(Prefsdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(Prefsdir)" || exit $$?; \
	done

uninstall-PrefsDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(Prefs_DATA)'; test -n "$(Prefsdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(Prefsdir)'; $(am__uninstall_files_from_dir)
install-SongsDATA: $(Songs_DATA)
	@$(NORMAL_INSTALL)
	@list='$(Songs_DATA)'; test -n "$(Songsdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(Songsdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(Songsdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(Songsdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(Songsdir)" || exit $$?; \
	done

uninstall-SongsDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(Songs_DATA)'; test -n "$(Songsdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(Songsdir)'; $(am__uninstall_files_from_dir)
install-Tune1DATA: $(Tune1_DATA)
	@$(NORMAL_INSTALL)
	@list='$(Tune1_DATA)'; test -n "$(Tune1dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(Tune1dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(Tune1dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(Tune1dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(Tune1dir)" || exit $$?; \
	done

uninstall-Tune1DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(Tune1_DATA)'; test -n "$(Tune1dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(Tune1dir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files
distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) $(AM_DISTCHECK_DVI_TARGET) \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(Prefsdir)" "$(DESTDIR)$(Songsdir)" "$(DESTDIR)$(Tune1dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool clean-local \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/LiveMusicApp-APlayMidi.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-AlsaUtils.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Chorder.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Connections.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-HIDGrab.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-HTML.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-LiveMusicApp.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-MyWidgets.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Player.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-PrefsFile.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-PrefsGui.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-RightMenuClick.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-SooperOSC.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Timers.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-transport.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-wmctrl.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-PrefsDATA install-SongsDATA install-Tune1DATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/LiveMusicApp-APlayMidi.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-AlsaUtils.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Chorder.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Connections.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-HIDGrab.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-HTML.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-LiveMusicApp.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-MyWidgets.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Player.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-PrefsFile.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-PrefsGui.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-RightMenuClick.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-SooperOSC.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-Timers.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-transport.Po
	-rm -f ./$(DEPDIR)/LiveMusicApp-wmctrl.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-PrefsDATA uninstall-SongsDATA \
	uninstall-Tune1DATA uninstall-binPROGRAMS

.MAKE: install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	clean-libtool clean-local cscope cscopelist-am ctags ctags-am \
	dist dist-all dist-bzip2 dist-gzip dist-lzip dist-shar \
	dist-tarZ dist-xz dist-zip dist-zstd distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-libtool distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-PrefsDATA install-SongsDATA install-Tune1DATA \
	install-am install-binPROGRAMS install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-exec-hook install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-PrefsDATA uninstall-SongsDATA \
	uninstall-Tune1DATA uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


#Songsdir = "$(Prefsdir)/MySongs/"
# Songs_DATA = DefaultSongs/*

# Songsdir = "$(HOME)/MySongs/"
# Songs_DATA = DefaultSongs/*
#Songs_DATA = DefaultSongs/* -c -m 644

# install-data-local:

install-exec-hook:
#	rsync -avrx "./MySongs" $(Prefsdir)
#	rsync -avrx "./LiveMusicRes/" $(Prefsdir)

# 	$(MKDIR_P) $(Prefsdir)
# 	$(MKDIR_P) $(Songsdir)
# 	chmod a+rw $(Songsdir)
# 	chown $$USER:$$USER $(Songsdir)
# 	chmod a+rw $(Prefsdir)
# 	chown $$USER:$$USER $(Prefsdir)
# 	rsync -avrx "./DefaultSongs/" "$(HOME)/MySongs/"
# 	rsync -avrx "./LiveMusicRes/" "$(HOME)/.config/LiveMusicApp/"

clean-local:
	rm -f *.0 src/*.o

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
