[
  ["/usr/local/lib/ladspa/autotalent.so", 0, 4262, "autotalent"],
  ["/usr/local/lib/ladspa/chebstortion_1430.so", 0, 1430, "chebstortion"],
  ["/usr/local/lib/ladspa/comb_1190.so", 0, 1190, "comb"],
  ["/usr/local/lib/ladspa/crossover_dist_1404.so", 0, 1404, "crossoverDist"],
  ["http://drobilla.net/plugins/fomp/cs_chorus1", -1, 0, "CS Chorus 1"],
  ["http://drobilla.net/plugins/fomp/cs_chorus2", -1, 0, "CS Chorus 2"],
  ["/usr/local/lib/ladspa/dyson_compress_1403.so", 0, 1403, "dysonCompress"],
  ["/usr/local/lib/ladspa/foldover_1213.so", 0, 1213, "foldover"],
  ["/usr/local/lib/ladspa/formant_filter_4300.so", 0, 4300, "formant_vc"],
  ["/usr/local/lib/ladspa/gong_1424.so", 0, 1424, "gong"],
  ["/usr/local/lib/ladspa/gsm_1215.so", 0, 1215, "gsm"],
  ["/usr/local/lib/ladspa/guitarix_IR.so", 0, 4065, "guitarix_IR"],
  ["http://guitarix.sourceforge.net/plugins/gxautowah#autowah", -1, 0, "GxAutoWah"],
  ["http://guitarix.sourceforge.net/plugins/gx_bmp_#_bmp_", -1, 0, "GxBigMuffPi"],
  ["http://guitarix.sourceforge.net/plugins/gx_cstb_#_cstb_", -1, 0, "GxColorSound Tonebender"],
  ["http://guitarix.sourceforge.net/plugins/gx_compressor#_compressor", -1, 0, "GxCompressor"],
  ["http://guitarix.sourceforge.net/plugins/gx_duck_delay_#_duck_delay_", -1, 0, "Gxduck_delay"],
  ["http://guitarix.sourceforge.net/plugins/gx_mbcompressor_#_mbcompressor_", -1, 0, "GxMultiBandCompressor"],
  ["http://guitarix.sourceforge.net/plugins/gx_oc_2_#_oc_2_", -1, 0, "Gxoc_2"],
  ["http://guitarix.sourceforge.net/plugins/gx_rangem_#_rangem_", -1, 0, "GxRangeMaster"],
  ["http://guitarix.sourceforge.net/plugins/gx_shimmizita_#_shimmizita_", -1, 0, "Gxshimmizita"],
  ["http://guitarix.sourceforge.net/plugins/gx_studiopre#studiopre", -1, 0, "Gx Studio Preamp Mono"],
  ["http://guitarix.sourceforge.net/plugins/gx_susta_#_susta_", -1, 0, "GxSustainer"],
  ["http://guitarix.sourceforge.net/plugins/gxts9#ts9sim", -1, 0, "GxTubeScreamer"],
  ["/usr/local/lib/ladspa/cmt.so", 32, 1845, "hard_gate"],
  ["/usr/local/lib/ladspa/harmonic_gen_1220.so", 0, 1220, "harmonicGen"],
  ["/usr/local/lib/ladspa/hermes_filter_1200.so", 0, 1200, "hermesFilter"],
  ["/usr/local/lib/ladspa/pitch_scale_1194.so", 0, 1194, "pitchScaleHQ"],
  ["/usr/local/lib/ladspa/imp_1199.so", 0, 1199, "imp"],
  ["/usr/local/lib/ladspa/masher_4310.so", 0, 4310, "ssm_masher"],
  ["/usr/local/lib/ladspa/multivoice_chorus_1201.so", 0, 1201, "multivoiceChorus"],
  ["/usr/local/lib/ladspa/pitch_scale_1193.so", 0, 1193, "pitchScale"],
  ["/usr/local/lib/ladspa/ladspa-rubberband.so", 0, 2979, "rubberband-pitchshifter-mono"],
  ["/usr/local/lib/ladspa/tap_chorusflanger.so", 0, 2159, "tap_chorusflanger"],
  ["/usr/local/lib/ladspa/tap_pitch.so", 0, 2150, "tap_pitch"],
  ["/usr/local/lib/ladspa/transient_1206.so", 0, 1206, "transient"],
  ["/usr/local/lib/ladspa/vlevel-ladspa.so", 0, 1981, "vlevel_mono"],
  ["/usr/local/lib/ladspa/vocoder_1337.so", 0, 1337, "vocoder"],
  ["/usr/local/lib/ladspa/shaper_1187.so", 0, 1187, "shaper"],
  ["/usr/local/lib/ladspa/zm1_1428.so", 0, 1428, "zm1"],
  ["/usr/local/lib/ladspa/ZamAutoSat-ladspa.so", 0, 1515405652, "ZamAutoSat"],
  ["/usr/local/lib/ladspa/ZamHeadX2-ladspa.so", 0, 1514685490, "ZamHeadX2"]
]
