[
  ["/usr/lib/ladspa/am_pitchshift_1433.so", 0, 1433, "amPitchshift"],
  ["/usr/lib/ladspa/divider_1186.so", 0, 1186, "divider"],
  ["/usr/lib/ladspa/calf.so", 7, 34049, "MultiChorus"],
  ["http://guitarix.sourceforge.net/plugins/gx_cstb_#_cstb_", -1, 0, "GxColorSound Tonebender"],
  ["http://guitarix.sourceforge.net/plugins/gx_expander#_expander", -1, 0, "GxExpander"],
  ["http://guitarix.sourceforge.net/plugins/gx_oc_2_#_oc_2_", -1, 0, "Gxoc_2"],
  ["http://guitarix.sourceforge.net/plugins/gx_rangem_#_rangem_", -1, 0, "GxRangeMaster"],
  ["http://guitarix.sourceforge.net/plugins/gx_scream_#_scream_", -1, 0, "GxScreamingBird"],
  ["http://guitarix.sourceforge.net/plugins/gx_shimmizita_#_shimmizita_", -1, 0, "Gxshimmizita"],
  ["/usr/lib/ladspa/hard_limiter_1413.so", 0, 1413, "hardLimiter"],
  ["/usr/lib/ladspa/harmonic_gen_1220.so", 0, 1220, "harmonicGen"],
  ["/usr/lib/ladspa/cmt.so", 34, 1098, "identity_audio"],
  ["/usr/lib/ladspa/imp_1199.so", 0, 1199, "imp"],
  ["/usr/lib/ladspa/matrix_spatialiser_1422.so", 0, 1422, "matrixSpatialiser"],
  ["/usr/lib/ladspa/multivoice_chorus_1201.so", 0, 1201, "multivoiceChorus"],
  ["/usr/lib/ladspa/pitch_scale_1193.so", 0, 1193, "pitchScale"],
  ["/usr/lib/ladspa/tap_chorusflanger.so", 0, 2159, "tap_chorusflanger"],
  ["/usr/lib/ladspa/tap_doubler.so", 0, 2156, "tap_doubler"],
  ["/usr/lib/ladspa/tap_pitch.so", 0, 2150, "tap_pitch"],
  ["/usr/lib/ladspa/tap_tubewarmth.so", 0, 2158, "tap_tubewarmth"],
  ["/usr/lib/ladspa/cmt.so", 62, 1224, "vcf303"],
  ["/usr/lib/ladspa/vocoder_1337.so", 0, 1337, "vocoder"]
]
