#! /bin/sh
#---------------------------------------------------------------------
#
#	File: 	CopyToEffects
#
#	Contains: 	
#
#
#	Written By: 	Elias Keshishoglou on Fri Feb 27 22:13:12 PST 2015
#
#	Copyright ©: 	2015 Elias Keshishoglou all rights reserved.
#
#
#---------------------------------------------------------------------#
# DestDir="/home/GDriveKesh/Music/LiveEffects/"
DestDir="/home/Dropbox/LiveEffects/"

cp LiveMusicApp  ${DestDir}
cp ./Scripts/KeepLiveMusicRunning.sh  ${DestDir}
# rsync -avrx ./LiveMusicRes/ ${DestDir}LiveMusicRes/
# rsync -avrx ./LiveMusicRes/ ~/.config/LiveMusicApp/
# cp ./Scripts/GuitarEffects ${DestDir}
# cp /home/elias/workspace/MusicFiles/ExtractHTML ${DestDir}
#cp /home/elias/workspace/MusicFiles/MyTuxGuitar ${DestDir}
#cp /home/elias/workspace/MusicFiles/jack-plumbing ${DestDir}"/Prefs/"

echo "Copy back to source."
# rsync -avrx ${DestDir}"/Prefs/" ./Prefs/

# /home/elias/.config/rncbc.org/Qsynth.conf
# /home/elias/.sooperlooper
# /home/elias/.config/guitarix



# ~/.hydrogen/hydrogen.conf
# ~/.sooperlooper
# ~/.config/guitarix