#!/bin/bash
#-------------------------------------------
#
#   File:   GuitarEffects
#
#   Contains:   This file starts up the live performance as well as practice
#       applications and automatically configures them.
#
#
#   Written By:     Elias Keshishoglou on Thu Jun 25 20:49:03 PDT 2009
#
#   Copyright :    2009-2021 Elias Keshishoglou all rights reserved.
#
#
#-------------------------------------------#

function Delay {
    echo "Delay "`expr $1 \* 3`" "$1
    sleep `expr $1 \* 2`
}

#-------------------------------------------#
#
# Find the devices that Jack should connect with.
#
#-------------------------------------------#
function FindDevice {
    
    # ( 32 / 48000 ) * 3 = 2
    # ( 64 / 48000 ) * 3 = 4
    # ( 128 / 48000 ) * 3 = 8
    # ( 256 / 48000 ) * 3 = 16
    # ( 512 / 48000 ) * 3 = 32
    # ( 32 / 96000 ) * 3 = 1
    # ( 64 / 96000 ) * 3 = 2
    # ( 96 / 96000 ) * 3 = 3
    # ( 128 / 96000 ) * 3 = 4
    # ( 256 / 96000 ) * 3 = 8
    # ( 512 / 96000 ) * 3 = 16
    
    MainInputPort=1
    
    # Get a list of all devices that can record
    export DeviceList=`arecord -l | tail -n +2`
    
    # Check for USB devices
    export USBDevice="`echo "$DeviceList" | grep -i USB`"
    export USBName=`echo $USBDevice | cut -d "[" -f2 | cut -d "]" -f1`
    HaveUSBInt=$?
    if [ "$HaveUSBInt" -eq 0 ]; then
        echo "We have a USB device "$USBDevice
    fi
    HaveUSBInt=1
    export USBCardNum=`echo "$USBDevice" | grep -Po '(?<=card )\W*\K[^ :]*'`
    export USBDeviceNum=`echo "$USBDevice" | grep -Po '(?<=device )\W*\K[^ :]*'`
    echo " -- "
    echo "D: "$USBDevice" N: "$USBName" CN "$USBCardNum" CI "$USBDeviceNum
    
    # export SndCardHW=`./HwSndParams hw:$USBCardNum`
    
    #   ./HwSndParams hw:1 | grep "Supported" | awk '{print $3}'
    #   ./HwSndParams hw:1 | grep "Sample" | awk '{print $3}'
    
    RouterNameIn="LiveMusic"
    RouterNameOut="LiveMusic"
    DrumNameIn="Hydrogen"
    DrumNameOut="Hydrogen"
    MidiGuitarInputPort="gx_head_amp"
    
    # Piano connections
    KeyBoardMidi="UX16"
    
    # Midi controller
    #   PedalBoardIn="Uno"
    KeyBoardMidi="Uno"
    Sequencer="rosegarden"
    
    AudioSampleRate=48000
    JBuffer=256
    JPeriod=2
    
    # Let's check the hardware we have and see what we can do
    # The Default is none.
    AudioDevice="None"
    DeviceAdder=""
    
    # Look for the Intel device, usually the built in sound device
    Device="Intel"
    echo $DeviceList | grep $Device >/dev/null
    if [ "$?" -eq 0 -a $HaveUSBInt -ne 0 ]; then
        echo "We have " $Device  >> $LogFile
        AudioDevice=$Device
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        #     MidiGuitarInputPort="rakarrack"
        PedalBoardIn="Midilink"
        PedalBoardIn="UX16"
        PedalBoardIn="Uno"
        MidiOut="Midilink"
        AudioSampleRate=48000
        JBuffer=1024
        JPeriod=3
    fi
    
    # ART Tube Pre and Alesis MultiMix
    Device="USB Audio CODEC"
    echo $DeviceList | grep "${Device}"  >/dev/null
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioDevice=$Device
        #       AudioSampleRate=96000
        
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        MidiGuitarInputPort=$Device
        AudioSampleRate=48000
        JBuffer=128
        JPeriod=3
    fi
    
    # If we have the edirol UA-25 use that instead.
    Device="UA-25"
    echo $DeviceList | grep "${Device}" >/dev/null
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioDevice=$Device
        #       AudioSampleRate=96000
        
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        MidiGuitarInputPort=$Device
        AudioSampleRate=48000
        JBuffer=128
        JPeriod=3
        QJackProfile="UA-25"
        
    fi
    
    # If we have the Quattro use that instead.
    Device="Quattro"
    echo $DeviceList | grep "${Device}"  >/dev/null
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioDevice=$Device
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        QJackProfile="Quattro"
    fi
    
    # If we have the Quattro use that instead.
    Device="UA-30"
    echo $DeviceList | grep "${Device}"  >/dev/null
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioDevice=$Device
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        QJackProfile="UA-30"
    fi
    
    # If we have the M-Audio FastTrack Pro use that instead.
    Device="FastTrack"
    echo $DeviceList | grep "${Device}"  >/dev/null
    if [ "$?" -eq 0 ]; then
        
        echo "We have " $Device >> $LogFile
        #   jackd -p128 -t1000 -dalsa -dhw:2,1 -r44100 -p128 -n4
        AudioDevice=$Device
        # This is the Audio interface
        AudioInDevice=$Device
        AudioOutDevice=$Device
        MidiGuitarInputPort=$Device
        DeviceAdder=",1"
        QJackProfile="FastTrack"
    fi
    
    # If we have the Alesis IO4
    Device="iO4"
    echo $DeviceList | grep "${Device}"  >/dev/null
    if [ "$?" -eq 0 ]; then
        
        echo "We have " $Device >> $LogFile
        AudioSampleRate=48000
        AudioDevice=$Device
        AudioInDevice=$Device
        AudioOutDevice=$Device
        JBuffer=128
        JPeriod=3
        
        MidiGuitarInputPort="iO4"
        PedalBoardIn="iO4"
        MidiOut="iO4"
        #     DeviceAdder=",1"
        QJackProfile="iO4"
    fi
    
    # If we have the Alesis Mini IO
    Device="iO Hub"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        # AudioSampleRate=96000
        AudioSampleRate=48000
        AudioDevice="$Device"
        AudioInDevice=$Device
        AudioOutDevice=$Device
        QJackProfile="iO_Hub"
    fi
    
    # If we have the Focuswrite scarlett
    Device="Scarlett Solo USB"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        #   AudioSampleRate=48000
        # AudioSampleRate=96000
        # JBuffer=256
        # JPeriod=2
        AudioSampleRate=48000
        JBuffer=128
        JPeriod=3
        
        AudioDevice="$Device"
        AudioInDevice="Scarlett Solo"
        AudioOutDevice="Scarlett Solo"
        MainInputPort=2
        QJackProfile="Scarlett"
    fi
    
    # If we have the iRig 2
    Device="iRig HD 2"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioSampleRate=48000
#        AudioSampleRate=96000
        JBuffer=128
        JPeriod=3
        # AudioSampleRate=192000
        AudioDevice="$Device"
        AudioInDevice="$Device"
        AudioOutDevice="$Device"
        QJackProfile="iRig"
    fi
    
    
    # If we have the NUX Pocket port
    Device="USB PnP Sound Device"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        echo "We have " $Device" "$USBDevice" "$USBName
        
        export USBDevice="`echo "$DeviceList" | grep -i "$Device" `"
        export USBName=`echo $USBDevice | cut -d "[" -f2 | cut -d "]" -f1`
        export USBCardNum=`echo "$USBDevice" | grep -Po '(?<=card )\W*\K[^ :]*'`
        export USBDeviceNum=`echo "$USBDevice" | grep -Po '(?<=device )\W*\K[^ :]*'`
        echo "We have 1" $Device" "$USBDevice" "$USBName
        
        # mplayer crackling at 96K,64,2
        # AudioSampleRate=96000
        # JBuffer=128
        # JPeriod=4
        
        AudioSampleRate=48000
        JBuffer=64
        JPeriod=3
        
        # AudioSampleRate=192000
        AudioDevice="$Device"
        AudioInDevice="$Device"
        AudioOutDevice="$Device"
        QJackProfile="USBPnP"
    fi
    
    # If we have the NUX Pocket port
    Device="NUX USB Audio"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        echo "We have " $Device" "$USBDevice" "$USBName
        #  idVendor           0x20b1 XMOS Ltd
        #  idProduct          0x2018
        
        
        export USBDevice="`echo "$DeviceList" | grep -i "$Device" `"
        export USBName=`echo $USBDevice | cut -d "[" -f2 | cut -d "]" -f1`
        export USBCardNum=`echo "$USBDevice" | grep -Po '(?<=card )\W*\K[^ :]*'`
        export USBDeviceNum=`echo "$USBDevice" | grep -Po '(?<=device )\W*\K[^ :]*'`
        echo "We have 1" $Device" "$USBDevice" "$USBName
        
        # mplayer crackling at 96K,64,2
        # AudioSampleRate=96000
        # JBuffer=128
        # JPeriod=4
        
        AudioSampleRate=48000
        JBuffer=64
        JPeriod=3
        
        # AudioSampleRate=192000
        AudioDevice="$Device"
        AudioInDevice="$Device"
        AudioOutDevice="$Device"
        amixer -c $USBCardNum sset 'Mic',0 2032
        amixer -c $USBCardNum sset 'NUX USB Audio 2.0 ',0 2032
        QJackProfile="Nux96"
    fi
    
    # If we are n a Raspberry PI with the PISound card.
    Device="pisound"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        AudioSampleRate=48000
        # AudioSampleRate=96000
        #       AudioSampleRate=192000
        AudioDevice="$Device"
        AudioInDevice="$Device"
        AudioOutDevice="$Device"
        QJackProfile="pisound"
    fi
    
    # If we have
    Device="USB Advanced Audio Device"
    echo $DeviceList | grep "${Device}"
    if [ "$?" -eq 0 ]; then
        echo "We have " $Device >> $LogFile
        # AudioSampleRate=48000
        # JBuffer=64
        # JPeriod=3
        
        AudioSampleRate=96000
        JBuffer=256
        JPeriod=3
        
        #       AudioSampleRate=192000
        AudioDevice="$Device"
        AudioInDevice="$Device"
        AudioOutDevice="$Device"
    fi
    
    # Check if we have found something.
    if test "$AudioDevice" = "None"; then
        echo "We found no interfaces"  >> $LogFile
        #        exit 1
    fi
    
    echo "Audio Interface is: " ${AudioInDevice}" " ${AudioOutDevice}  >> $LogFile
    # Get the port numbers of the interface
    AudioInHW=`arecord -l | grep -m 1 "${AudioInDevice}" | awk '{ print $2}' | cut -d":" -f1`
    AudioOutHW=`arecord -l | grep -m 1 "${AudioOutDevice}" | awk '{ print $2}' | cut -d":" -f1`
    export RecordFileName=/home/Music/Rehearsals/`date +"%Y%m%d"`
    echo "Audio Number is: " ${AudioInHW}" " ${AudioOutHW}  >> $LogFile
    
    #   Patchage takes a while to start so kick it off early.
    # Run the patch bay
    echo "***************** Starting Patch Bay"
    # patchage  > /dev/null 2>&1 &
    # catia > $LogFile 2>&1 &
    ${PatchBay} > $LogFile 2>&1 &
}

#-------------------------------------------#
#
# Set the Definitions
#
#-------------------------------------------#
function SetDefinitions {
    # This is the midi router for converting Program Change
    RouterNameIn="LiveMusic"
    RouterNameOut="LiveMusic"
    DrumNameIn="Hydrogen"
    DrumNameOut="Hydrogen"
    
    # Piano connections
    #   KeyBoardMidi="UX16"
    #   PedalBoardIn="Uno"
    KeyBoardMidi="Uno"
    
    Sequencer="rosegarden"
    
    echo "Audio Interface is: " ${AudioInDevice}  >> $LogFile
    # Get the port numbers of the interface
    AudioInHW=`arecord -l | grep -m 1 "${AudioInDevice}" | awk '{ print $2}' | cut -d":" -f1`
    AudioOutHW=`arecord -l | grep -m 1 "${AudioOutDevice}" | awk '{ print $2}' | cut -d":" -f1`
    
    # Record file name is based on date.
    export RecordFileName=/home/Music/Rehearsals/`date +"%Y%m%d"`
    
    #   if [ ! -d "$RecordFileName" ]; then
    #       echo -e "\nCreating \"$RecordFileName\"\n"
    #       cp -r /home/Music/Rehearsals/Template $RecordFileName
    #   fi
}

#-------------------------------------------#
#
# Startup Jack.
#
#-------------------------------------------#
function StartJack {
    
    if [[ $UsePipeWire == "Yes" ]]; then
        return
    fi


    # See if Jackd is already running
    if [ `ps -ew|grep -c jackd` != 0 ] ; then
        #        ps -ef | grep jackd | grep -v grep | awk '{print $2}' | xargs kill -9
        #        Delay 1
        KillJackOnExit=false
        echo "Jack is already running"
        return
    fi
    
    # https://wiki.linuxaudio.org/wiki/list_of_jack_frame_period_settings_ideal_for_usb_interface
    #
    if [ "${AudioInDevice}" == "iO4" ] ; then
        #       jackd -R -t5000 -dalsa -Chw:$AudioInHW$DeviceAdder -Phw:$AudioOutHW$DeviceAdder -r$AudioSampleRate -p128 -n3 &
        echo "Audio i04, run jack twice"
        jackd -R -t5000 -dalsa -Chw:$AudioInHW$DeviceAdder -Phw:$AudioOutHW$DeviceAdder -r$AudioSampleRate -p64 -n2 &
        sleep 1
        /home/ebin/killall jackd
        sleep 1
    fi
    
    # Now start jack.
    echo "****************" >> $LogFile
    echo "Starting Jack"   >> $LogFile
    # Now start jack.
    echo "****************"
    echo "Starting Jack"
    
    
    if [ "foo1" = "foo" ]; then
        qjackctl -p "${QJackProfile}" -s &
        echo "Starting qjackctl "${QJackProfile}
        
        sleep 5
        
    else
        
        nice -18 jackd \
        -R \
        -P89 \
        -t5000 \
        -dalsa \
        -S \
        -Chw:$AudioInHW$DeviceAdder \
        -Phw:$AudioOutHW$DeviceAdder \
        -r$AudioSampleRate \
        -p$JBuffer \
        -n$JPeriod >> $LogFile 2>&1 &
        
        echo "****************"
        echo "****************"  >> $LogFile
        echo "nice -18 jackd "
        #echo "-c 2 Max Capture Channels"
        echo "-R Realtime"
        echo "-P89 High Priority"
        echo "-t5000 Timeout mode"
        echo "-dalsa Use the Alsa backend"
        echo "-S Try and use 16 bits"
        #echo "--midi seq Use Alsa Sequencer"
        echo "-Chw:"$AudioInHW$DeviceAdder
        echo "-Phw:"$AudioOutHW$DeviceAdder
        echo "-r"$AudioSampleRate
        echo "-p"$JBuffer
        echo "-n"$JPeriod
        echo "****************" >> $LogFile
        echo "****************"
        
    fi
    
    
    if [ `ps -ew | grep -c jackd` == 0 ] ; then
        echo "Sleeping for jackd"  >> $LogFile
        Delay 1
    fi
    
    if [ `ps -ew | grep -c jackd` == 0 ] ; then
        echo "Sleeping for jackd...Again"  >> $LogFile
        Delay 1
    fi
    
    # Route all normal applications thru Jack also
    # pulseaudio --kill
    # pulseaudio -nF $EffectsDir/jack.pa &
    # indicator-sound pulseaudio pulseaudio-esound-compat
    # pulseaudio-module-bluetooth pulseaudio-module-jack pulseaudio-module-x11
    # pulseaudio -L module-jack-sink -L module-jack-source
    
    
    # for Debug
    if test "${2}" = "System"; then
        exit 0
    fi
}


#-------------------------------------------#
#
# Startup Set Up Connections
#
#-------------------------------------------#
function SetUpConnections {
    
    # ********************************
    # **** Alsa sound if no USB interface
    # ********************************
    
    # Turn on Line input as source.
    #   amixer cset numid=8,iface=MIXER,name='Input Source' 0
    
    # Turn on the Headphone output
    amixer cset numid=6,iface=MIXER,name='Headphone Playback Switch' 1
    
    # Turn on the Master output
    amixer cset numid=10,iface=MIXER,name='Master Playback Switch' 1
    
    # Set the input mode to be a line level signal not a mic.
    amixer cset numid=5,iface=MIXER,name='Mic Jack Mode' 1
    
    amixer sset "Mic Boost" 0
    #   amixer sset "Capture" 70
    amixer cset name='Capture Switch' 2
    
    # Max out the USB Device.
    amixer -c 1 sset 'PCM' 128
    
    amixer sset 'Master' 65535
    
    # ********************************
    # **** Definitions
    # ********************************
    MainOut1="jack-volume:input_1"
    MainOut2="jack-volume:input_2"
    MainOut3="jack-volume:input_3"
    MainOut4="jack-volume:input_4"
    
    PedalBoardName="EliasPedal3"
    KeyBoardMidi="Uno"
    MidiGuitarMidi="LiveMusic"
    
    # ********************************
    # **** Alsa midi connections
    # ********************************
    aconnect "TriplePlay Connect":"0" "LiveMidi":2
    aconnect "Fishman TriplePlay":"0" "LiveMidi":2

    # for Keyboard
    aconnect "USB Uno MIDI Interface":"0" "LiveMidi":2

    # Pedal Versions
    aconnect "EliasPedal3":"0" "LiveMusic":"0"
    aconnect "EliasGuitar":"0" "LiveMusic":"0"
    aconnect "EliasMidi":"0" "LiveMusic":"0"
    aconnect "LPD8":"0" "LiveDAW":"1"
    
    # Midi
    aconnect "LiveMusic Output":"0" "FLUID Synth (qsynth)":"0"
    # Metronome
    aconnect "LiveMusic Output":"5" "FLUID Synth (qsynth)":"0"
    # Drum Looper
    aconnect "LiveMusic Output":"8" "FLUID Synth (qsynth)":"0"

    # Temp control for sooper
#    aconnect "LiveMusic Output":"2" "sooperlooper":"0"
    
    # TO Pedalboard
    aconnect "LiveMusic Output":"6" "EliasPedal3":"0"
    # To Guitar Controller
    aconnect "LiveMusic Output":"6" "EliasGuitar":"0"
    aconnect "LiveMusic Output":"6" "EliasMidi":"0"
    # To KorgNano
    aconnect "LiveMusic Output":"7" "LPD8":"0"
    aconnect "LiveMusic Output":"7" "nanoKONTROL2":"0"
    aconnect "LiveMusic Output":"6" "NMSVE":"0"
    aconnect "LiveMusic Output":"7" "Reloop KeyFadr":"0"


    aconnect "Midi Through":"0" "FLUID Synth (qsynth)":"0"
    aconnect "Reloop KeyFadr":"0" "LiveDAW":"1"
    aconnect "nanoKONTROL2":"0" "LiveDAW":"1"
    aconnect "NMSVE":"0" "LiveMusic":"0"
    aconnect "Fishman TriplePlay":0 "MusE":0
    
    
    aconnect -d "Fishman TriplePlay":"0" "FLUID Synth (qsynth)":"0"
    aconnect -d "Fishman TriplePlay":"1" "FLUID Synth (qsynth)":"0"
    aconnect -d "TriplePlay Connect":"0" "FLUID Synth (qsynth)":"0"
    aconnect -d "TriplePlay Connect":"1" "FLUID Synth (qsynth)":"0"
    aconnect -d "EliasGuitar":"0" "FLUID Synth (qsynth)":"0"
    aconnect -d "System":"1" "FLUID Synth (qsynth)":"0"
    aconnect -d "Midi Through":"1" "FLUID Synth (qsynth)":"0"   
    aconnect -d "Midi Through":"2" "FLUID Synth (qsynth)":"0"   
    aconnect -d "Midi Through":"3" "FLUID Synth (qsynth)":"0"   
    aconnect -d "nanoKONTROL2":"0" "FLUID Synth (qsynth)":"0"   
    aconnect -d "sooperlooper":"0" "FLUID Synth (qsynth)":"0"   

    # ********************************
    # **** Jack audio and midi connections
    # ********************************
    # To find devices
    # jack_lsp -c
    
    # Midi Sound generato
    MidiSoundOut=`jack_lsp -c |  grep "FLUID" | tail -1`
    
    # Connect Jack_Volume to Main
    jack_connect jack-volume:output_1 system:playback_1
    jack_connect jack-volume:output_1 system:playback_2
    jack_connect jack-volume:output_2 system:playback_1
    jack_connect jack-volume:output_2 system:playback_2
    jack_connect jack-volume:output_3 system:playback_1
    jack_connect jack-volume:output_3 system:playback_2
    jack_connect jack-volume:output_4 system:playback_1
    jack_connect jack-volume:output_4 system:playback_2
    
    
    # Guitar in goes to effects Rack
    
    if [ $MainInputPort == 2 ]; then
        
        echo "jack_connect system:capture_1 gx_head_amp:in_1"
        #    jack_connect system:capture_1 gx_head_amp:in_0
        jack_connect system:capture_2 gx_head_amp:in_0
        jack_connect system:capture_1 system:playback_1
        jack_connect system:capture_1 system:playback_2
        jack_disconnect system:capture_2 system:playback_2
        jack_disconnect system:capture_2 system:playback_1
    else
        jack_connect system:capture_1 gx_head_amp:in_0
        jack_connect system:capture_2 system:playback_1
        jack_connect system:capture_2 system:playback_2
        jack_disconnect system:capture_1 system:playback_2
        jack_disconnect system:capture_1 system:playback_1
        
    fi
    
    echo "Guitarix Audio to Jack Volume"
    jack_connect gx_head_fx:out_0 $MainOut1
    jack_connect gx_head_fx:out_1 $MainOut1
    jack_disconnect gx_head_fx:out_1 system:playback_1
    jack_disconnect gx_head_fx:out_0 system:playback_2
    
    #    jack_connect gx_head_fx:out_0 loud_comp_mono:in
    #    jack_connect gx_head_fx:out_1 loud_comp_mono:in
    #    jack_connect loud_comp_mono:out $MainOut1
    
    
    # Connect Guitarix out to looper in
    jack_connect gx_head_fx:out_1 sooperlooper:common_in_1
    #   jack_connect gx_head_fx:out_2 sooperlooper:common_in_2
    
    # Connect the Looper to the main outputs
    jack_connect sooperlooper:common_out_1 $MainOut4
    jack_connect sooperlooper:common_out_1 $MainOut4
    jack_connect sooperlooper:common_out_2 $MainOut4
    jack_connect sooperlooper:common_out_2 $MainOut4
    
    # Soundfont player get connected to the Main playback device.
    jack_connect qsynth:left jack-volume:input_2
    jack_connect qsynth:right jack-volume:input_2
    jack_disconnect qsynth:left system:playback_1
    jack_disconnect qsynth:right system:playback_2
    
    # Connect qsynth to the Looper.
    jack_connect qsynth:left sooperlooper:common_in_1
    jack_connect qsynth:left sooperlooper:common_in_2
    
    # Drum Machine
    jack_connect Hydrogen:out_L sooperlooper:common_in_1
    jack_connect Hydrogen:out_R sooperlooper:common_in_2
    jack_connect Hydrogen:out_L $MainOut2
    jack_connect Hydrogen:out_R $MainOut2
    
    jack_connect strawberry:out_jackaudiosink-1_1 $MainOut3
    jack_connect strawberry:out_jackaudiosink-1_1 $MainOut3
    
    jack_connect Guitarix:out_1 "ardour:Audio 1/in 1"
    jack_connect gx_head_fx:out_1 "ardour:Audio 1/in 1"
    aconnect "LiveMusic Output":1 GuitBridge:0
    jack_connect "GuitBridge:capture" gx_head_amp:midi_in_1
    
    #    aconnect "TriplePlay Connect":0 MuseBridge:0
    #    aconnect "Fishman TriplePlay":0  MuseBridge:0
    #    jack_connect "MuseBridge:capture" mscore:mscore-midiin-1
    # Transport out
    #    aconnect "LiveMusic Output":3 Mamba:input
    
    # Tempo out
    #   aconnect "LiveMusic Output":4 Mamba:input
    
    #   jack_connect "Mamba:out" "a2j:FLUID Synth (qsynth) (playback): Synth input port (qsynth:0)"    # jack_connect "Mamba:out" "MambaBridge:playback"
    # aconnect MambaBridge:capture "FLUID Synth":0
    
    
    # Muse Connection
    aconnect "Fishman TriplePlay":0  MusE:0
    aconnect "MusE":0 "FLUID Synth":0
    jack_connect "MusE:Out 1-0" "system:playback_1"
    jack_connect "MusE:Out 1-1" "system:playback_1"


    if [[ $UsePipeWire == "Yes" ]]; then
        PipeConnect.sh
    fi

}

#-------------------------------------------#
#
# Find USB device
#
#-------------------------------------------#
function FindUSB {
    
    cd /sys/bus/usb/devices
    for f in `ls `
    do
        if [ -f $f/product ]; then
            MyDevice=`cat $f/product`
            if [ "$MyDevice" == "Trackball" ]; then
                echo $f
                if [ $1 == "off" ] ; then
                    echo "0" > /sys/bus/usb/devices/$f/power/state
                else
                    echo "1" > /sys/bus/usb/devices/$f/power/state
                fi

                echo "$MyDevice" | grep -i audio
                if [ $? == 0 ]; then
                    echo "$MyDevice"

                fi
            fi
        fi
    done
}

#-------------------------------------------#
#
# Set up Music Applications
#
#-------------------------------------------#
function SetUpApplications {
    
    if test "${SoundSynth}" = "true"; then
        # Launch the Soundfont player.
        echo "Starting qsynth "$PipeStart   >> $LogFile
        echo "Starting qsynth "$PipeStart
        nice -15 `QT_STYLE_OVERRIDE=QtCurve ${PipeStart} qsynth -g 1.0  -o  synth.midi-bank-select=mma` >> $LogFile 2>&1 &
    fi

    if [ `hostname` == "livemusic" ]; then
        ButtonSize=96
    else
        ButtonSize=140
    fi

    # Midi Router
    if test "${MidiController}" = "true"; then
        echo "Starting Midi Router"  >> $LogFile
        echo "Starting Midi Router"
        echo "Pipewire option "$PipeOption
        # nice -15 `GTK_THEME=LiveMusicTheme LiveMusicApp \
        # -e -v $PipeOption \
        # -l $ButtonLayout \
        # -f $ButtonSize \
        # -j "${AudioOutDevice}"` \
        # >> $LogFile 2>&1 &
    fi
    
    # This is the Guitar effects processor
    if test "${GuitarEffects}" = "true"; then
        echo "Starting Guitar Effects"  >> $LogFile
        MusicApps.sh EffectsProcessorApp >> $LogFile 2>&1 &
        #   rakarrack -b $EffectsDir/EliasBankNew.rkrb -l $EffectsDir/Elias1.rkr &
        Delay 2
    fi
    
    if test "${Looper}" = "true"; then
        # Set the first Desktop to use.
       $PipeStart slgui -L /home/elias/MySongs/Looper/EliasLooper.slsess -P=9951 >> $LogFile &
    fi
    
    if test "${InternetJamStart}" = "true"; then
        # Internet
        $InternetJam -l /home/MySongs/Prefs/sonobus_elias.sonobus &
    fi
    
    if test "${Ardour}" = "true"; then
        # We are going to record
         $PipeStart ardour /home/Music/Rehearsals/`date +"%Y%m%d"` &
    fi
    
    if test "${MP3Player}" = "true"; then
        # Set the first Desktop to use.
       QT_STYLE_OVERRIDE=QtCurve  $PipeStart strawberry &
    fi
    
    if test "${MusePlayer}" = "true"; then
        # Set the first Desktop to use.
        MusicApps.sh MidPlay >> $LogFile 2>&1 &
 #       QT_STYLE_OVERRIDE=QtCurve muse &
    fi
    
    if test "${MuseScore}" = "true"; then
        # Set the first Desktop to use.
        MusicApps.sh Score >> $LogFile 2>&1 &
#        QT_STYLE_OVERRIDE=QtCurve musescore3 &
    fi
    
    # External viewer, not used anymore
    if test "${MusicViewer}" = "true"; then
        if test "${Group}" = "fusion"; then
            okular /home/Music/BandStuff/Fusion/FusionBlueCharts.pdf
        else
            konqueror --open-session FusionBlue &
            #         okular /home/Music/BandStuff/Poblano/WebCharts/PoblanoCharts1.pdf
        fi
    fi
    
    # Are we practicing ? then run the sequence
    if test "${Rosegarden}" = "true"; then
         $PipeStart rosegarden &
        Delay 2
    fi
    
    if test "${TabPlayer}" = "true"; then
        tuxguitar &
    fi
    
    # Do we launch the drum machine .
    if test "${Hydrogen}" = "true"; then
        $PipeStart hydrogen -k GMKit -s  /home/elias/MySongs/Drums/JustFunky.h2song &
    fi
    
    # mamba /home/Music/MidiFiles/MidiLoops/funk4.mid &
    
    Delay 2
    
    
    # This script check for a failed app
    # and will relaunch it
    if test "${BackroundChecker}" = "true"; then
        KeepLiveMusicRunning.sh "LiveMusicApp" "${EffectsProcessorApp}"  $UsePipeWire &
    fi
    #  kdialog --progressbar  "Elias Guitar Effects Hints" 0
}

#-------------------------------------------#
#
# Move apps to correct placement
#
#-------------------------------------------#
function SetPlacement {
    
    MaxOffSet=1368
    ExtID=`xinput list | grep -Po 'Atmel.*id=\K[0-9]+'`
    xinput map-to-output $ExtID LVDS1
    
    #   ExtID=`xinput list | grep -Po 'ILITEK.*id=\K[0-9]+'`
    #   xinput map-to-output $ExtID HDMI1
    
    xrandr | grep "HDMI1 connected"
    ExtraMonitor="$?"
    
    # On home PC spread it out
    if [ `hostname` == "Keshie" ] || 
       [ `hostname` == "KeshP15" ]; then
        echo "Keshie"
        AnalogDesktop=5
        LiveMusicAppDesktop=5
        LooperDesktop=$LiveMusicAppDesktop
        MidiDesktop=$AnalogDesktop
        PatchageDesktop=7
        PlayerDesktop=7
        DrumDesktop=7
        YOffset=1080
        YOffset=900
        
        #        if [ "$?" -eq "1" ]
        
        if [ "$ExtraMonitor" -eq "1" ]; then
            YOffset=0
            ExMonitor=0
            echo "External Monitor Not Found"
        else
            echo "External Monitor Found"
            ExMonitor=1
        fi
        
        SetPlacement1920
    elif [ `hostname` == "Music" ]; then
        echo "Music"
        AnalogDesktop=0
        LiveMusicAppDesktop=1
        LooperDesktop=$AnalogDesktop
        MidiDesktop=$AnalogDesktop
        PatchageDesktop=3
        PlayerDesktop=2
        DrumDesktop=3
        YOffset=0
        
        SetPlacement1200
    else
        echo "Default PC"
        AnalogDesktop=0
        LiveMusicAppDesktop=1
        PatchageDesktop=3
        PlayerDesktop=2
        LooperDesktop=$AnalogDesktop
        MidiDesktop=$AnalogDesktop
        DrumDesktop=3
        SetPlacement1920
    fi
    
    if test "${OneScreeOnly}" = "true"; then
        echo "One screen only "
        AnalogDesktop=7
        LiveMusicAppDesktop=$AnalogDesktop
        PatchageDesktop=$AnalogDesktop
        PlayerDesktop=$AnalogDesktop
        LooperDesktop=$AnalogDesktop
        MidiDesktop=$AnalogDesktop
        DrumDesktop=$AnalogDesktop
        MaxOffSet=1920
        SetPlacement1920
    fi
    
    # # Check for Digitizer, tells us where we are.
    # xinput | grep "ILITEK"
    # if [ "$?" = "0" ] ; then
    #     echo "Found GeChic"
    #     ExtID=`xinput list | grep -Po 'ILITEK.*id=\K[0-9]+'`
    #     xinput map-to-output $ExtID HDMI1
    #     XOffset=0
    #     YOffset=1080
    #     NewOffset=`expr $XOffset + 1050`
    #     MaxOffSet=`expr 1368+1920`
    #     PlayerDesktop=4
    #     PatchageDesktop=4
    #     LooperDesktop=7
    #     AnalogDesktop=5
    #     MidiDesktop=5
    #     SetPlacement1920
    # else
    #     xinput | grep "PixArtImaging"
    #     if [ "$?" = "0" ] ; then
    #         echo "Found ViewSonic"
    #         xrandr --output HDMI1 --mode 1920x1080 --pos 1366x0
    
    #         ExtID=`xinput list | grep -Po 'PixArtImaging.*id=\K[0-9]+'`
    #         xinput map-to-output $ExtID HDMI1
    
    #         XOffset=1370
    #         NewOffset=`expr $XOffset + 1050`
    #         MaxOffSet=`expr 1368+1920`
    #         SetPlacement1920
    #     else
    #         SetPlacement1920
    
    #     fi
    # fi
    wmctrl -a $LiveMusicAppDesktop
}

#-------------------------------------------#
#
# Move apps to correct placement
#
#-------------------------------------------#
function SetPlacement1920 {
    set -x
    
    echo "1920 Placement Offset  "$XOffset" "$YOffset
    NewOffset=`expr $XOffset + 0`

    if [ "$ExtraMonitor" -eq "1" ]; then

        wmctrl -r ${EffectsProcessorWM} -t $AnalogDesktop
 #       wmctrl -r ${EffectsProcessorWM} -e 0,600,0,700,860
        wmctrl -r ${EffectsProcessorWM} -e 0,10,0,700,1350

        wmctrl -F -r LiveMusicApp_1 -t $LiveMusicAppDesktop
        wmctrl -F -r LiveMusicApp_1 -e 0,200,0,2250,1300
        
        wmctrl -r SooperLooper -t $LooperDesktop
        wmctrl -r SooperLooper -e 0,586,420,1000,450
        
        wmctrl -r qsynth -e 0,640,80,1600,400
        wmctrl -r qsynth -t $MidiDesktop
    else
        wmctrl -r ${EffectsProcessorWM} -t $AnalogDesktop
        wmctrl -r ${EffectsProcessorWM} -e 0,0,0,700,1350

        wmctrl -F -r LiveMusicApp_1 -t $LiveMusicAppDesktop
    #    wmctrl -F -r LiveMusicApp_1 -e 0,0,$YOffset,1850,1050
        wmctrl -F -r LiveMusicApp_1 -e 0,100,0,2300,1350
        
        wmctrl -r SooperLooper -t $LooperDesktop
        wmctrl -r SooperLooper -e 0,1350,420,1100,450
        
        wmctrl -r qsynth -e 0,1450,80,1400,400
        wmctrl -r qsynth -t $MidiDesktop
    fi
    
    #       wmctrl -r strawberry -e 0,$NewOffset,350,1000,700
    wmctrl -r strawberry -e 0,$XOffset,$YOffset,1920,1000
    wmctrl -r strawberry -t $PlayerDesktop
    
    NewOffset=`expr $XOffset + 1000`
    wmctrl -r TuxGuitar -t $PlayerDesktop
    wmctrl -r TuxGuitar -e 0,0,0,1920,1000
    
    wmctrl -r Hydrogen -t $DrumDesktop
    wmctrl -r Hydrogen -e 0,0,0,1600,900
    
    wmctrl -r Patchage -t $PatchageDesktop
    wmctrl -r Patchage -e 0,0,0,1700,1000
    
    wmctrl -r ${PatchBayName} -t $PatchageDesktop
    wmctrl -r ${PatchBayName} -e 0,0,0,1200,850
    
    wmctrl -r QjackCtl -e 0,640,80,600,125
    wmctrl -r "Graph — QjackCtl" -e 0,0,940,1800,1000
    wmctrl -r QjackCtl -t $MidiDesktop
    
    set +x
}

#-------------------------------------------#
#
# Move apps to correct placement
#
#-------------------------------------------#
function SetPlacement1600 {
    set -x
    
    echo "1600 Placement Offset "$XOffset
    NewOffset=`expr $XOffset + 0`
    wmctrl -r ${EffectsProcessorWM} -e 0,$NewOffset,30,850,650
    wmctrl -r ${EffectsProcessorWM} -t $AnalogDesktop
    
    wmctrl -r LiveMusicApp_1 -e 0,`expr $NewOffset + 550`,10,1340,800
    wmctrl -r LiveMusicApp_1 -t $LiveMusicAppDesktop
    
    wmctrl -r Patchage -e 0,80,10,1200,700
    wmctrl -r Patchage -t $PatchageDesktop
    
    wmctrl -r SooperLooper -e 0,`expr $NewOffset + 900`,475,1000,575
    wmctrl -r SooperLooper -t $LooperDesktop
    
    wmctrl -r qsynth -e 0,80,0,1200,700
    wmctrl -r qsynth -t $MidiDesktop
    
    NewOffset=`expr $XOffset + 0`
    wmctrl -r strawberry -e 0,$NewOffset,350,1000,700
    wmctrl -r strawberry -t $PlayerDesktop
    
    NewOffset=`expr $XOffset + 1000`
    wmctrl -r TuxGuitar -e 0,$NewOffset,250,900,800
    wmctrl -r TuxGuitar -t $PlayerDesktop
    
    wmctrl -r QjackCtl -e 0,640,80,600,125
    wmctrl -r QjackCtl -t $MidiDesktop
}

#-------------------------------------------#
#
# Move apps to correct placement
#
#-------------------------------------------#
function SetPlacement1200 {
    
    echo "1200 Placement Offset "$XOffset
    NewOffset=`expr $XOffset + 0`
    wmctrl -r ${EffectsProcessorWM} -e 1,0,30,850,760
    wmctrl -r ${EffectsProcessorWM} -t $AnalogDesktop
    
    wmctrl -r LiveMusicApp_1 -e 0,0,10,1300,760
    wmctrl -r LiveMusicApp_1 -t $LiveMusicAppDesktop
    
    wmctrl -r Patchage -e 0,80,10,1000,700
    wmctrl -r Patchage -t $PatchageDesktop
    
    wmctrl -r SooperLooper -t $LooperDesktop
    wmctrl -r SooperLooper -e 0,80,0,900,600
    
    wmctrl -r qsynth -e 0,640,0,1600,400
    wmctrl -r qsynth -t $MidiDesktop
    
    wmctrl -r strawberry -e 1,0,150,1000,600
    wmctrl -r strawberry -t $PlayerDesktop
    
    wmctrl -r TuxGuitar -e 0,366,250,1000,500
    wmctrl -r TuxGuitar -t $PlayerDesktop
    
    wmctrl -r QjackCtl -e 0,640,80,600,125
    wmctrl -r QjackCtl -t $MidiDesktop
}

function StopEverything {
    echo "Closing down Effects"

    killall KeepLiveMusicRunning.sh
KillAll guitarix
KillAll guitarix
KillAll guitarix
    wmctrl -c ${EffectsProcessorWM}
    wmctrl -c LiveMusicApp_1
    wmctrl -c Patchage
    wmctrl -c SooperLooper
    wmctrl -c qsynth
    wmctrl -c strawberry
    wmctrl -c QjackCtl

    killall patchage
    killall -I ${EffectsProcessorName}
    killall qsynth
    killall ardour2
    killall jack-volume
    killall kmetronome
    killall qmidiroute
    killall mididings
    killall guitarix
    killall receivemidi
    killall rosegarden
    killall hydrogen
    killall qsynth
    killall strawberry
    killall okular
    killall livedings
    killall jack-volume
    killall LiveMusicApp
    killall sooperlooper
    killall slgui
    killall tuxguitar
    killall smplayer
    killall a2jmidid
    killall $InternetJam
    
    killall kmidimon
    killall kdialog
    killall konqueror
    killall smplayer
    killall mplayer
    killall tuxguitar
    killall aqualung
    killall mididings
    killall a2jmidid
    killall gedit
    killall $InternetJam
    
    
    killall -I ${EffectsProcessorName}
    killall ${PatchBay}
    KillAll catia
    killall a2jmidid
    killall guitarix
    #    FAHClient --send-unpause "LiveMusicApp_Done"
    
    #    if test "${KillJackOnExit}" = "true"; then
    echo "Killing Jack"
    killall jack-plumbing
    killall qjackctl
    KillAll jackd
    KillAll jack
    killall jackdbus
    sleep 3
    killall jack-plumbing
    killall qjackctl
    KillAll jackd
    killall jackdbus
    #    fi
    xset s on
    xset +dpms
    powerprofilesctl set balanced
    exit 0
}

#-------------------------------------------#
#
# Main, start of script
#
#-------------------------------------------#
# set -x
#

echo "Line "$1
# Set Default values
GuitarEffects=true
EffectsProcessorName="Guitarix"
EffectsProcessorApp="guitarixOld"
EffectsProcessorWM="Guitarix: gx_head"
# PatchBay="carla"
PatchBay="qpwgraph"
PatchBayName="qpwgraph"
InternetJam="sonobus"

MidiController=true
Rosegarden=false
Hydrogen=false
Ardour=false
MP3Player=false
MusePlayer=false
MuseScore=false
Looper=false
MusicViewer=false
WeAreDebugging=false
KillJackOnExit=true
#LogFile=~/.config/LiveMusicApp/LogGuitar.txt
LogFile=/dev/tty
# JackFile=LogJack
TabPlayer=false
XOffset=0
JamStik=false
ButtonLayout=1
OneScreeOnly=false
BackroundChecker=true
InternetJamStart=false
SoundSynth=true
Version="2.1.5"


PipeActive=`ps aux | grep pipewire1 | wc -l`

if [ $PipeActive > 1 ];  then
echo "Pipe found"
UsePipeWire="Yes"
else 
echo "Pipe Not found"
UsePipeWire="No"
fi


if [[ $UsePipeWire == "Yes" ]]; then
PipeStart="pw-jack " 
PipeOption=" -w " 
else
PipeStart="" 
PipeOption="" 
#PIPEWIRE_LATENCY=128/48000
fi

# systemctl --user restart pipewire pipewire-pulse wireplumber

powerprofilesctl set performance
xinput set-prop --type=int --format=32 17 "Evdev Axis Calibration" 0 5464 0 4050
# sudo echo 5 > /proc/sys/vm/swappiness
# sudo echo -n performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

# Right of
# xinput set-prop --type=int --format=32 17 "Evdev Axis Calibration" -5500 4100 0 4100

# Exec=env WINEPREFIX="/home/elias/.wine64" wine64 MIDIGuitar2-64bit.exe
echo "--------------------------------------------" >> $LogFile
echo `date` >> $LogFile
echo $PATH >> $LogFile
echo "--------------------------------------------" >> $LogFile
# Parse command line options.
while getopts "abcdefgijkhrpmnovlswt" OPT; do
    #    echo "hello "$OPT
    case "$OPT" in
        h)
            echo "
        a - Ardour
        b - Adjust Placement
        c - Make Connections
        d - Drum Machine
        e - Launcher Execute
        g - Generate Charts
        i - Internet
        j - JamStik
        k - Debugging
        l - Looper
        m - Music Player
        n - Muse Player
        o - Muse Score
        p - PFD viewer
        r - Rosegarden
        s - Stop everything
        t - Tab Editor
        v - version
            w - Working Scoring"
            exit 0
        ;;
        v)
            echo "`basename $0` "$Version
            echo "2019-31-03"
            exit 0
        ;;
        a)
            echo "Ardour2"
            Ardour=true
        ;;
        b)
            SetPlacement
            exit 0
        ;;
        c)
            #            FindDevice
            #            SetDefinitions
            SetUpConnections
            exit 0
        ;;
        d)
            echo "Drum Machine"
            Hydrogen=true
        ;;
        e)
            # if the script is called
            # twice exit.
            LogFile=~/.config/LiveMusicApp/LogGuitar.txt
            
#	    echo $PATH >> $LogFile
#  		exit 0
 	    pid=`pgrep guitarix`
            if [ -z $pid ]
            then
                echo "GuitarEffects Auto 1"
            else
                StopEverything
            fi
            
            pid=`pgrep LiveMusicApp`
            if [ -z $pid ]
            then
                MP3Player=true
                MidiController=true
                GuitarEffects=true
                BackroundChecker=true
                SoundSynth=true
                Looper=true
                #                Hydrogen=true
            else
                StopEverything
            fi
        ;;
        
        f)
            echo "Test"
            Rosegarden=false
            MidiController=true
            GuitarEffects=false
            MusicViewer=false
            OneScreeOnly=true
            TabPlayer=false
            Looper=true
            Hydrogen=true
            BackroundChecker=false
            MP3Player=false
            SoundSynth=true
        ;;
        g)
            # LiveMusicReplacePDF.py /home/elias/MySongs/FusionBlue/
            LiveMusicCharts.py /home/MySongs/FusionBlue/ -f -c -i -r
        ;;
        i)
            InternetJamStart=true
        ;;
        j)
            echo "JamStik"
            JamStik=true
        ;;
        k)
            echo "Debugging"
            WeAreDebugging=true
            BackroundChecker=false
            MP3Player=false
            MidiController=true
            GuitarEffects=true
            SoundSynth=true
            Looper=true
        ;;
        l)
            echo "Looper"
            Looper=true
        ;;
        m)
            echo "MP3 Player"
            MP3Player=true
        ;;
        n)
            echo "Muse"
            MusePlayer=true
        ;;
        o)
            echo "Muse Score"
            MuseScore=true
        ;;
        
        r)
            echo "Rosegarden"
            Rosegarden=true
        ;;
        t)
            echo "Tab Player"
            TabPlayer=true
        ;;
        l)
            echo "Looper"
            Looper=true
        ;;
        p)
            echo "PDF"
            MusicViewer=true
        ;;
        w)
            echo "PDF"
            Rosegarden=true
            MidiController=false
            GuitarEffects=false
            MusicViewer=false
        ;;
        s)
            StopEverything
            exit 0
        ;;
        o)
            Group=$OPTARG
        ;;
        ?)
            # getopts issues an error message
            echo $USAGE >&2
            exit 1
        ;;
    esac
done

RunCount=`pgrep -c LiveMusicApp `
if [[ RunCount -gt 1 ]]; then
    echo "********** Multiple Version running, killing."
    exit 1
fi

#  the computer from screen saving.
xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device
qdbus org.freedesktop.ScreenSaver /ScreenSaver Inhibit NULL NULL
qdbus org.freedesktop.ScreenSaver /ScreenSaver SetActive false
# FAHClient --send-pause "LiveMusicApp_Running"
killall receivemidi

# Remove the switches we parsed above.
shift `expr $OPTIND - 1`

# Access additional arguments as usual through
# variables $@, $*, $1, $2, etc. or using this loop:
for PARAM; do
    echo $PARAM
done

date  > $LogFile
export IAM=`whoami`

# cpupower frequency-info

# Try and find what device we should use.
FindDevice

echo -n "System Timer "
cat /sys/devices/system/clocksource/clocksource0/current_clocksource

echo -n "Timer Speed "
cat /sys/class/rtc/rtc0/max_user_freq

GXSize=`wc -c /home/elias/.config/guitarix/gx_head_rc | awk '{print $1}'`
if [ $GXSize -ge 150000 ];
then
    zenity --warning \
    --text=" gx_head_rc too large "$GXSize
    # The end (connections) of the gx_head_rc file get's large.
    # jack_connections remove.
fi

# Set the definitions for the functions.
echo "Set Definitions"
SetDefinitions

# Start up Jack
echo "Start Jack"
StartJack


# If at first you don't succeed ....
if [ `ps -ew | grep -c jackd` == 0 ] ; then
    StartJack
fi

if [[ $UsePipeWire == "No" ]]; then
    if [ `ps -ew | grep -c jackd` == 0 ] ; then
        zenity --warning \
        --text=" Can\'t Start Jack"
        exit 1
    fi

    # If jackd is still not running then exit.
    if [ `ps -ew|grep -c jackd` == 0 ] ; then
        echo "Exiting, could not launch Sound System"  >> $LogFile
        exit 1
    fi
fi

if [ `ps -ew | grep -c jack-volume` == 0 ] ; then
    # Jack can be a bit slow to come up.
    echo " About to Start Jack-Volume"
    $PipeStart  nice -18 jack-volume -p 9952 -n 4  >> $LogFile 2>&1 &
fi

if [ `ps -ew | grep -c jack-plumbing` == 0 ] ; then
    $PipeStart  jack-plumbing /home/MySongs/Prefs/jack-plumbing >> $LogFile 2>&1 &
fi

# In case the OSC port didn't close.
NetSt=`netstat -np | grep -i Live`
OSCPID=`echo $NetSt awk -F '[ /]'  '{ print $8}'`
kill $OSCPID

echo "***************** Starting SetUpApplications"
# Set up the other applications.
Delay 3

# -e to enable hardware interfaces as well.
# a2jmidid -e > $LogFile 2>&1 &

a2jmidi_bridge "GuitBridge" &
#       j2amidi_bridge "MambaBridge" &
#    a2jmidid -u &
# a2jmidi_bridge "MuseBridge" &

SetUpApplications
Delay 1 

echo "***************** Starting SetUpConnections"
# Set up the mixer levels and the interconnection between devices.
SetUpConnections

# Put apps in the right place/desktop
echo "***************** Starting SetPlacement"
SetPlacement

sleep 8

# Set up the mixer levels and the interconnection between devices.
SetUpConnections

echo "***************** Starting SetPlacement"
# Put apps in the right place/desktop
SetPlacement

exit 0

# Check for file size on this:
# /home/elias/.config/guitarix/gx_head_rc
#
# lsp-plugins-loud-comp-mono -c /home/elias/LoudCompensation.cfg
#loud_comp_mono:in
#loud_comp_mono:out


# GDK_BACKEND=broadway BROADWAY_DISPLAY=:5 gtk3-demo

# Pipewire
# pw-metadata -n settings 0 clock.force-quantum 128
# PIPEWIRE_LATENCY="128/48000" pw-jack reaper

